/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/admin/courses": {
    /**
     * 全講座一覧
     * @description システム全体の全コース検索。ステータスや売上情報でのソートも可能。
     */
    get: operations["API_ADMIN_01"];
    /**
     * 講座代理作成（運営）
     * @description operator/root_operator が講座を代理作成。ownerUserId（=指定講師）を必須指定する。初期status=draft（非公開）。承認免除。公開は講師側のpublish操作で行う（publish時にCourseMember.role=instructor→instructor_ownerへ昇格）。
     */
    post: operations["API_ADMIN_02"];
  };
  "/api/v1/admin/courses/{courseId}": {
    /**
     * 講座削除（運営）
     * @description コースの論理削除。status=archivedに変更。受講者への影響を考慮し、既存受講データは保持。
     */
    delete: operations["API_ADMIN_04"];
    /**
     * 講座代理編集（運営）
     * @description 運営によるコース情報の代理編集。title, description, catalogVisibility, visibility, ownerUserId を変更可能。
     */
    patch: operations["API_ADMIN_03"];
  };
  "/api/v1/admin/courses/{courseId}/approve": {
    /**
     * 講座承認・審査
     * @description 公開審査中の講座を承認。statusをactiveに変更しLPを公開する。
     */
    post: operations["API_ADMIN_05"];
  };
  "/api/v1/admin/courses/{courseId}/freeze": {
    /**
     * コース凍結（運営）
     * @description 規約違反等の際に発動。全更新APIを423 Lockedにする。
     *
     * ---
     *
     * コースを凍結すると、全ユーザーのアクセスを423 Lockedにする
     */
    post: operations["API_ADMIN_06"];
  };
  "/api/v1/admin/courses/{courseId}/unfreeze": {
    /**
     * コース凍結解除（運営）
     * @description コースの凍結を解除し、通常アクセスを復帰させる
     */
    post: operations["API_ADMIN_07"];
  };
  "/api/v1/admin/audit/courses/{courseId}": {
    /**
     * [監査]凍結講座閲覧
     * @description 凍結中の秘匿コンテンツを精査。誰が閲覧したかのログを強制記録。
     */
    get: operations["API_ADMIN_08"];
  };
  "/api/v1/admin/users": {
    /**
     * 全ユーザー一覧
     * @description プラットフォーム上の全アカウントを横断検索。globalRole, isActive, deletedAt でフィルタ可能。
     */
    get: operations["API_ADMIN_09"];
    /**
     * ユーザー作成（受講者/講師）
     * @description 運営による受講者/講師の代理登録。globalRoleはlearnerまたはinstructorのみ指定可能。operator/root_operatorの登録は /api/v1/admin/operators 経由で行う。
     */
    post: operations["API_ADMIN_10"];
  };
  "/api/v1/admin/users/{userId}": {
    /**
     * ユーザー論理削除
     * @description ユーザーの論理削除。deletedAtをセットしisActive=falseに変更。物理削除は行わない。
     */
    delete: operations["API_ADMIN_12"];
    /**
     * ユーザー編集
     * @description 運営による受講者/講師情報の代理編集。email, name, globalRole(learner/instructor), isActive を変更可能。
     */
    patch: operations["API_ADMIN_11"];
  };
  "/api/v1/admin/users/{userId}/freeze": {
    /**
     * ユーザー凍結(BAN)
     * @description 悪質ユーザーのシステム全体へのアクセス禁止処理。
     */
    post: operations["API_ADMIN_13"];
  };
  "/api/v1/admin/users/{userId}/unfreeze": {
    /**
     * ユーザー凍結解除
     * @description 凍結中ユーザーのシステム全体へのアクセス禁止を解除する。
     */
    post: operations["API_ADMIN_14"];
  };
  "/api/v1/admin/operators": {
    /**
     * 運営スタッフ一覧
     * @description globalRoleがoperator/root_operatorのユーザー一覧。
     */
    get: operations["API_ADMIN_15"];
    /**
     * 運営スタッフ追加
     * @description 既存ユーザーのglobalRoleをoperator/root_operatorに変更し、運営スタッフとして登録。監査ログ対象。
     */
    post: operations["API_ADMIN_16"];
  };
  "/api/v1/admin/operators/{userId}": {
    /**
     * 運営スタッフ削除（論理削除）
     * @description 運営スタッフの論理削除。deletedAtをセットしisActive=falseに変更。globalRoleは変更しない（復帰時の参考情報として保持）。
     */
    delete: operations["API_ADMIN_18"];
    /**
     * 運営スタッフ編集（ロール変更）
     * @description 運営スタッフのglobalRoleをoperator⇔root_operatorで変更。
     */
    patch: operations["API_ADMIN_17"];
  };
  "/api/v1/admin/payments": {
    /**
     * 決済履歴一覧
     * @description Stripe経由の全決済ログ、返金対応状況、売上動向を監視。
     */
    get: operations["API_ADMIN_19"];
  };
  "/api/v1/admin/channels/{channelId}/freeze": {
    /**
     * チャンネル凍結（運営）
     * @description チャンネルを凍結
     */
    post: operations["API_ADMIN_20"];
  };
  "/api/v1/admin/channels/{channelId}/unfreeze": {
    /**
     * チャンネル凍結解除（運営）
     * @description チャンネルの凍結を解除
     */
    post: operations["API_ADMIN_21"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      id: string;
      email: string | null;
      name: string | null;
      isActive: boolean;
      /** Format: date-time */
      deletedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      globalRole: components["schemas"]["GlobalRole"];
    };
    UserCreateRequest: {
      /** Format: email */
      email: string;
      name: string;
      /**
       * @description 受講者(learner)または講師(instructor)のみ指定可能。operator/root_operatorは /operators 経由。
       * @enum {string}
       */
      globalRole: "learner" | "instructor";
    };
    UserUpdateRequest: {
      /** Format: email */
      email?: string;
      name?: string;
      /**
       * @description 受講者(learner)または講師(instructor)のみ指定可能。
       * @enum {string}
       */
      globalRole?: "learner" | "instructor";
      isActive?: boolean;
    };
    UserAdminView: {
      user: components["schemas"]["User"];
      status: string;
      /** Format: date-time */
      lastLoginAt?: string | null;
    };
    UserListResponse: {
      items: components["schemas"]["UserAdminView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    OperatorAdminView: {
      /** @description User.id */
      id: string;
      email?: string | null;
      name?: string | null;
      /**
       * @description operator または root_operator
       * @enum {string}
       */
      globalRole: "operator" | "root_operator";
      isActive: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    OperatorListResponse: {
      items: components["schemas"]["OperatorAdminView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    OperatorCreateRequest: {
      /** @description 運営スタッフに昇格させる既存ユーザーのID */
      userId: string;
      /**
       * @description operator または root_operator
       * @enum {string}
       */
      globalRole: "operator" | "root_operator";
    };
    OperatorUpdateRequest: {
      /**
       * @description operator または root_operator
       * @enum {string}
       */
      globalRole: "operator" | "root_operator";
    };
    Course: {
      id: string;
      title: string;
      description?: string | null;
      ownerUserId: string;
      /** @enum {string} */
      catalogVisibility: "public_listed" | "public_unlisted" | "private";
      /** @enum {string} */
      visibility: "public" | "instructors_only";
      isFrozen: boolean;
      /** Format: date-time */
      frozenAt?: string | null;
      frozenByUserId?: string | null;
      freezeReason?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** @description 作成者ユーザーID（instructor or operator/root_operator） */
      createdByUserId: string;
      /**
       * @description 講座ステータス
       * @enum {string}
       */
      status: "draft" | "pending_approval" | "active" | "archived";
      /** Format: date-time */
      approvalRequestedAt?: string | null;
      /** Format: date-time */
      approvedAt?: string | null;
      approvedByUserId?: string | null;
    };
    AdminCourseCreateRequest: {
      title: string;
      description?: string;
      /** @description このコースのオーナー講師（必須）。初期CourseMemberロールはinstructorとして仮与。公開（publish）時にinstructor_ownerへ昇格する。 */
      ownerUserId: string;
      /** @enum {string} */
      catalogVisibility?: "public_listed" | "public_unlisted" | "private";
      /** @enum {string} */
      visibility?: "public" | "instructors_only";
    };
    AdminCourseUpdateRequest: {
      title?: string;
      description?: string;
      ownerUserId?: string;
      /** @enum {string} */
      catalogVisibility?: "public_listed" | "public_unlisted" | "private";
      /** @enum {string} */
      visibility?: "public" | "instructors_only";
    };
    CourseDetailView: components["schemas"]["Course"];
    CourseListResponse: {
      items: components["schemas"]["Course"][];
      meta?: components["schemas"]["ListMeta"];
    };
    CourseChannel: {
      id: string;
      courseId: string;
      /** @enum {string} */
      type: "assignment" | "one_on_one" | "announcement" | "general";
      /** @enum {string} */
      postingMode: "mixed" | "threads_only";
      isFrozen: boolean;
      name?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseChannelDetailView: components["schemas"]["CourseChannel"];
    PaymentSummaryView: {
      id: string;
      userId: string;
      courseId?: string | null;
      amount: number;
      currency: string;
      status: string;
      provider: string;
      /** Format: date-time */
      paidAt?: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    PaymentListResponse: {
      items: components["schemas"]["PaymentSummaryView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    GenericWriteRequest: {
      [key: string]: unknown;
    };
    GenericDetailView: {
      [key: string]: unknown;
    };
    GenericListResponse: {
      items: Record<string, never>[];
      meta?: components["schemas"]["ListMeta"];
    };
    SuccessResponse: {
      success: boolean;
      message?: string;
    };
    ErrorResponse: {
      statusCode: number;
      message: string;
      error?: string;
    };
    ListMeta: {
      totalCount: number;
      page: number;
      perPage: number;
      totalPages: number;
    };
    UserMeView: components["schemas"]["User"];
    /** @enum {string} */
    GlobalRole: "guest" | "learner" | "instructor" | "operator" | "root_operator";
    /** @enum {string} */
    OrderStatus: "pending" | "paid" | "cancelled" | "failed" | "refunded";
    /** @enum {string} */
    SubmissionStatus: "draft" | "submitted" | "returned" | "graded";
    /** @enum {string} */
    AuditEventType: "announcement_emergency_posted" | "course_frozen" | "course_unfrozen" | "channel_frozen" | "channel_unfrozen" | "dm_viewed_by_root_operator" | "course_created" | "course_approval_requested" | "course_approved" | "course_published" | "course_member_role_promoted" | "user_frozen" | "user_unfrozen" | "user_created" | "user_updated" | "user_deleted" | "operator_role_changed";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * 全講座一覧
   * @description システム全体の全コース検索。ステータスや売上情報でのソートも可能。
   */
  API_ADMIN_01: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseListResponse"];
        };
      };
    };
  };
  /**
   * 講座代理作成（運営）
   * @description operator/root_operator が講座を代理作成。ownerUserId（=指定講師）を必須指定する。初期status=draft（非公開）。承認免除。公開は講師側のpublish操作で行う（publish時にCourseMember.role=instructor→instructor_ownerへ昇格）。
   */
  API_ADMIN_02: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminCourseCreateRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["Course"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * 講座削除（運営）
   * @description コースの論理削除。status=archivedに変更。受講者への影響を考慮し、既存受講データは保持。
   */
  API_ADMIN_04: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * 講座代理編集（運営）
   * @description 運営によるコース情報の代理編集。title, description, catalogVisibility, visibility, ownerUserId を変更可能。
   */
  API_ADMIN_03: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminCourseUpdateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * 講座承認・審査
   * @description 公開審査中の講座を承認。statusをactiveに変更しLPを公開する。
   */
  API_ADMIN_05: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * コース凍結（運営）
   * @description 規約違反等の際に発動。全更新APIを423 Lockedにする。
   *
   * ---
   *
   * コースを凍結すると、全ユーザーのアクセスを423 Lockedにする
   */
  API_ADMIN_06: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * コース凍結解除（運営）
   * @description コースの凍結を解除し、通常アクセスを復帰させる
   */
  API_ADMIN_07: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * [監査]凍結講座閲覧
   * @description 凍結中の秘匿コンテンツを精査。誰が閲覧したかのログを強制記録。
   */
  API_ADMIN_08: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericDetailView"];
        };
      };
    };
  };
  /**
   * 全ユーザー一覧
   * @description プラットフォーム上の全アカウントを横断検索。globalRole, isActive, deletedAt でフィルタ可能。
   */
  API_ADMIN_09: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["UserListResponse"];
        };
      };
    };
  };
  /**
   * ユーザー作成（受講者/講師）
   * @description 運営による受講者/講師の代理登録。globalRoleはlearnerまたはinstructorのみ指定可能。operator/root_operatorの登録は /api/v1/admin/operators 経由で行う。
   */
  API_ADMIN_10: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreateRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict (email重複) */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * ユーザー論理削除
   * @description ユーザーの論理削除。deletedAtをセットしisActive=falseに変更。物理削除は行わない。
   */
  API_ADMIN_12: {
    parameters: {
      path: {
        userId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * ユーザー編集
   * @description 運営による受講者/講師情報の代理編集。email, name, globalRole(learner/instructor), isActive を変更可能。
   */
  API_ADMIN_11: {
    parameters: {
      path: {
        userId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict (email重複) */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * ユーザー凍結(BAN)
   * @description 悪質ユーザーのシステム全体へのアクセス禁止処理。
   */
  API_ADMIN_13: {
    parameters: {
      path: {
        userId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * ユーザー凍結解除
   * @description 凍結中ユーザーのシステム全体へのアクセス禁止を解除する。
   */
  API_ADMIN_14: {
    parameters: {
      path: {
        userId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * 運営スタッフ一覧
   * @description globalRoleがoperator/root_operatorのユーザー一覧。
   */
  API_ADMIN_15: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["OperatorListResponse"];
        };
      };
    };
  };
  /**
   * 運営スタッフ追加
   * @description 既存ユーザーのglobalRoleをoperator/root_operatorに変更し、運営スタッフとして登録。監査ログ対象。
   */
  API_ADMIN_16: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OperatorCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["OperatorAdminView"];
        };
      };
      /** @description Not Found（対象ユーザーが存在しない） */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * 運営スタッフ削除（論理削除）
   * @description 運営スタッフの論理削除。deletedAtをセットしisActive=falseに変更。globalRoleは変更しない（復帰時の参考情報として保持）。
   */
  API_ADMIN_18: {
    parameters: {
      path: {
        userId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * 運営スタッフ編集（ロール変更）
   * @description 運営スタッフのglobalRoleをoperator⇔root_operatorで変更。
   */
  API_ADMIN_17: {
    parameters: {
      path: {
        userId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OperatorUpdateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["OperatorAdminView"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  /**
   * 決済履歴一覧
   * @description Stripe経由の全決済ログ、返金対応状況、売上動向を監視。
   */
  API_ADMIN_19: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PaymentListResponse"];
        };
      };
    };
  };
  /**
   * チャンネル凍結（運営）
   * @description チャンネルを凍結
   */
  API_ADMIN_20: {
    parameters: {
      path: {
        channelId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseChannelDetailView"];
        };
      };
    };
  };
  /**
   * チャンネル凍結解除（運営）
   * @description チャンネルの凍結を解除
   */
  API_ADMIN_21: {
    parameters: {
      path: {
        channelId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseChannelDetailView"];
        };
      };
    };
  };
}
