/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/users/me": {
    /**
     * プロフィール取得
     * @description ログイン中ユーザー自身の基本情報（名前、アイコン、全体ロール、所属組織等）を取得する。
     */
    get: operations["API_007"];
    /**
     * プロフィール更新
     * @description 名前、アイコン画像URL、自己紹介等のプロフィール情報を更新する（image_33b70dのデザインを反映）。
     */
    put: operations["API_008"];
  };
  "/api/v1/users/me/password": {
    /**
     * PW変更
     * @description 現在のパスワードを検証した上で、新しいパスワードへ直接変更する。セキュリティ上、即時反映される。
     */
    put: operations["API_009"];
  };
  "/api/v1/notifications": {
    /**
     * 通知一覧取得
     * @description 自分宛の通知（返信、採点完了、ライブ予約、運営案内）を最新順に取得する（image_32dc7bのリスト用）。
     */
    get: operations["API_010"];
  };
  "/api/v1/notifications/{notificationId}/read": {
    /**
     * 通知既読化
     * @description 指定されたIDの通知を既読状態にする。UI上のバッジカウントを減らすトリガーとなる。
     */
    post: operations["API_011"];
  };
  "/api/v1/notifications/read-all": {
    /**
     * 通知一括既読
     * @description 全ての未読通知を一括で既読状態にする。
     */
    post: operations["API_012"];
  };
  "/api/v1/users/me/settings/notifications": {
    /**
     * 通知設定取得
     * @description メール通知、プッシュ通知のON/OFF、およびカテゴリ別の受け取り設定を取得する。
     */
    get: operations["API_013"];
    /**
     * 通知設定更新
     * @description 通知設定をユーザーの好みに合わせて更新する。
     */
    put: operations["API_014"];
  };
  "/api/v1/store/courses": {
    /**
     * 講座一覧取得
     * @description 公開中(active)の講座を検索・取得。1on1、セミナー、ブートキャンプのスタイルやカテゴリでフィルタが可能。
     */
    get: operations["API_015"];
  };
  "/api/v1/store/courses/{courseId}": {
    /**
     * 講座詳細取得
     * @description 未受講者向けLPデータ。アウトカム、前提条件、おすすめ、FAQ、日程スケジュールをすべて取得。
     */
    get: operations["API_016"];
  };
  "/api/v1/store/courses/{courseId}/apply": {
    /**
     * 講座申込(開始)
     * @description 講座への受講を申し込む。有料時はpending、無料時はactiveでEnrollmentを生成する。
     */
    post: operations["API_017"];
  };
  "/api/v1/payments/stripe/checkout": {
    /**
     * Stripeセッション生成
     * @description 有料講座の決済を開始するためのStripe URLを発行。コースがfrozen時は423でブロック。
     */
    post: operations["API_018"];
  };
  "/api/v1/learner/courses": {
    /**
     * マイ講座一覧
     * @description 自身が受講中、または過去に受講したすべての講座をリスト取得する。
     */
    get: operations["API_019"];
  };
  "/api/v1/learner/courses/{courseId}": {
    /**
     * 受講中講座詳細
     * @description 受講者用学習画面。最新の進捗、シラバス、受講者専用の連絡事項、解禁済み教材等を取得。
     */
    get: operations["API_020"];
  };
  "/api/v1/learner/enrollments/{enrollmentId}": {
    /**
     * 決済/申込状況確認
     * @description pending状態（決済確認中）からactiveになったかをポーリング/確認するためのAPI。
     */
    get: operations["API_021"];
  };
  "/api/v1/learner/courses/{courseId}/side-menu": {
    /**
     * サイドメニュー取得
     * @description チャットチャンネルと解禁済み課題レッスンを階層構造化して取得（image_3345d2を完全再現）。
     */
    get: operations["API_022"];
  };
  "/api/v1/learner/assignments": {
    /**
     * 自分の課題一覧
     * @description 自分が提出すべき、または提出済みのすべての課題を全講座横断で一覧取得する。
     */
    get: operations["API_023"];
  };
  "/api/v1/learner/assignments/{lessonId}": {
    /**
     * 課題詳細取得
     * @description 課題の設問内容、配布資料、現在の提出状況と講師からの最新フィードバックを取得する。
     */
    get: operations["API_024"];
  };
  "/api/v1/learner/lessons/{lessonId}/submissions": {
    /**
     * 課題提出
     * @description 回答を提出。自動的にassignmentチャンネル内に講師との返信用スレッドを生成する。
     */
    post: operations["API_025"];
  };
  "/api/v1/learner/records": {
    /**
     * 学習実績取得
     * @description 獲得した証明書、バッジ、修了した講座の最終成績や学習時間統計を一覧取得する。
     */
    get: operations["API_026"];
  };
  "/api/v1/learner/calendar": {
    /**
     * カレンダー取得
     * @description 受講している全講座のライブ予定、提出期限、面談予定をカレンダー形式(JSON)で取得。
     */
    get: operations["API_027"];
  };
  "/api/v1/learner/courses/{courseId}/complete": {
    /**
     * コース修了処理
     * @description 全レッスン完了時の最終修了申請。講師による最終確認が必要な場合、評価待ちへ遷移。
     */
    post: operations["API_028"];
  };
  "/api/v1/surveys/{surveyId}": {
    /**
     * アンケート取得
     * @description 講座内アンケートの設問（選択式、記述式）を取得する。
     */
    get: operations["API_029"];
  };
  "/api/v1/surveys/{surveyId}/responses": {
    /**
     * アンケート回答
     * @description アンケート回答を送信。423チェック対象。回答により教材解禁が連動する場合がある。
     */
    post: operations["API_030"];
  };
  "/api/v1/instructor/courses": {
    /**
     * 自講座一覧
     * @description 自分が管理、または講師として参加（担当）している全講座を一覧取得する。
     */
    get: operations["API_031"];
    /**
     * 講座新規作成（講師）
     * @description 講師がコースを新規作成。ownerUserId=作成者（サーバー側で自動設定、リクエストでの指定不可）。初期status=draft。CourseMember(role=instructor_owner)が自動作成される。公開にはrequest-approval→approve が必要。
     */
    post: operations["API_032"];
  };
  "/api/v1/instructor/courses/{courseId}": {
    /**
     * 講座詳細取得(管理)
     * @description 講師用管理画面。売上概況、受講者推移、下書き情報を含む管理用詳細データ。
     */
    get: operations["API_033"];
    /**
     * 講座情報更新
     * @description 講座のタイトル、LP、価格、募集期間、マーケティング項目を更新（image_33637a反映）。
     */
    put: operations["API_034"];
    /**
     * 講座削除(論理)
     * @description 講座を論理削除(archived)状態にする。既存の受講生には閲覧権限のみ残存させる。
     */
    delete: operations["API_035"];
  };
  "/api/v1/instructor/courses/{courseId}/request-approval": {
    /**
     * 承認申請
     * @description 運営へ公開審査を依頼。statusがpending_approvalとなり、以降承認まで423 Locked。
     */
    post: operations["API_036"];
  };
  "/api/v1/instructor/courses/{courseId}/publish": {
    /**
     * コース公開（講師）
     * @description ownerUserId一致の講師がコースを公開する。statusをactiveに変更。operator作成コースの場合、CourseMember.roleをinstructor→instructor_ownerへ昇格（委譲完了）。
     */
    post: operations["API_036B"];
  };
  "/api/v1/instructor/analytics/overview": {
    /**
     * 売上分析サマリ
     * @description 期間別の収益、成約率、受講生離脱ポイント等の分析サマリーを取得。
     */
    get: operations["API_037"];
  };
  "/api/v1/instructor/settings/payout": {
    /**
     * 振込先銀行設定
     * @description 講師への報酬振込先口座情報をStripe Connect等と連携して設定・更新。
     */
    put: operations["API_038"];
  };
  "/api/v1/instructor/courses/{courseId}/syllabus": {
    /**
     * シラバス構造取得
     * @description 編集中の章立てとレッスン構成をツリー形式で取得（image_32dd18の構成用）。
     */
    get: operations["API_039"];
  };
  "/api/v1/instructor/courses/{courseId}/sections": {
    /**
     * セクション追加
     * @description カリキュラム内に新しい「章」を追加。423チェック対象。
     */
    post: operations["API_040"];
  };
  "/api/v1/instructor/sections/{sectionId}": {
    /**
     * セクション編集
     * @description セクション名の変更、表示順の並び替え、および削除。
     */
    put: operations["API_041"];
    /**
     * セクション削除
     * @description 指定されたセクションと、配下のレッスン紐付けを削除（論理/物理）。
     */
    delete: operations["API_042"];
  };
  "/api/v1/instructor/sections/{sectionId}/lessons": {
    /**
     * レッスン作成
     * @description 指定セクションに新規レッスンを追加（座学/動画/課題/ライブ）（image_32dcf8反映）。
     */
    post: operations["API_043"];
  };
  "/api/v1/instructor/lessons/{lessonId}": {
    /**
     * レッスン詳細取得
     * @description 編集画面用。動画URL、リッチテキスト本文、課題要件、Drip設定の詳細。
     */
    get: operations["API_044"];
    /**
     * レッスン編集
     * @description コンテンツの修正、Drip(解禁日)、先行ロック条件の保存。423チェック対象。
     */
    put: operations["API_045"];
    /**
     * レッスン削除
     * @description レッスンをカリキュラムから削除。
     */
    delete: operations["API_046"];
  };
  "/api/v1/instructor/lessons/{lessonId}/live": {
    /**
     * ライブ配信設定
     * @description ZoomやYouTube LiveのURL、および配信日時の設定（カレンダー連動）。
     */
    put: operations["API_047"];
  };
  "/api/v1/instructor/courses/{courseId}/submissions": {
    /**
     * 提出一覧取得
     * @description 受講者別の課題進捗、未確認提出物、最終提出日時の一覧（image_32dcd7反映）。
     */
    get: operations["API_048"];
  };
  "/api/v1/instructor/submissions/{submissionId}/evaluation": {
    /**
     * 評価・採点実行
     * @description 提出物への合否、講評を送信。合格時は自動で次の教材を解禁。フィードバックはスレッドへ。
     */
    patch: operations["API_049"];
  };
  "/api/v1/instructor/courses/{courseId}/members": {
    /**
     * 受講者名簿取得
     * @description 全参加ユーザーの属性、現在の進捗状況、メールアドレス等の名簿取得。
     */
    get: operations["API_050"];
  };
  "/api/v1/instructor/courses/{courseId}/members/{userId}/role": {
    /**
     * 講座内ロール変更
     * @description 特定ユーザーの役割（講師、アシスタント、受講生）を動的に切り替え。
     */
    patch: operations["API_051"];
  };
  "/api/v1/instructor/courses/{courseId}/members/{userId}/revoke": {
    /**
     * 受講権限剥奪
     * @description 特定ユーザーの受講権限を剥奪（revoked）し、コンテンツへのアクセスを遮断。
     */
    post: operations["API_052"];
  };
  "/api/v1/instructor/courses/{courseId}/export": {
    /**
     * 受講者CSV出力
     * @description 受講者名簿と学習進捗データをCSV形式でエクスポートする。
     */
    get: operations["API_053"];
  };
  "/api/v1/courses/{courseId}/channels": {
    /**
     * チャンネル一覧取得
     * @description サイドメニュー構築用。general, announcement等のチャンネル種別を含む。
     */
    get: operations["API_054"];
    /**
     * チャンネル作成
     * @description コース内に新しいカスタムチャンネルを追加。
     */
    post: operations["API_055"];
  };
  "/api/v1/channels/{channelId}": {
    /**
     * チャンネル編集
     * @description チャンネル名、説明文、閲覧制限、アーカイブ状態の更新。
     */
    put: operations["API_056"];
    /**
     * チャンネル削除
     * @description チャンネルを論理削除。過去ログは監査用に保持。
     */
    delete: operations["API_057"];
  };
  "/api/v1/channels/{channelId}/messages": {
    /**
     * メッセージ履歴取得
     * @description スレッド親（ルート）メッセージの一覧取得。課題の相互閲覧可（image_32d9b1反映）。
     */
    get: operations["API_058"];
    /**
     * メッセージ投稿
     * @description チャンネルへの新規投稿。親メッセージとして保存。threads_onlyを強制適用。
     */
    post: operations["API_059"];
  };
  "/api/v1/messages/{messageId}/thread": {
    /**
     * スレッド詳細取得
     * @description 特定メッセージに紐づく返信メッセージ一覧（スレッドビュー）を全件取得。
     */
    get: operations["API_060"];
  };
  "/api/v1/messages/{messageId}/replies": {
    /**
     * スレッド返信投稿
     * @description 返信投稿(image_32d9b1)。announcementタイプは講師以外返信不可。
     */
    post: operations["API_061"];
  };
  "/api/v1/messages/{messageId}": {
    /**
     * メッセージ削除
     * @description 投稿の論理削除。返信がある場合は「削除されました」と表示。
     */
    delete: operations["API_063"];
    /**
     * メッセージ編集
     * @description 自分の投稿内容を修正。編集履歴を保持。423チェック対象。
     */
    patch: operations["API_062"];
  };
  "/api/v1/messages/{messageId}/reactions": {
    /**
     * リアクション追加
     * @description メッセージに対する絵文字リアクションの付与。423チェック対象。
     */
    post: operations["API_064"];
  };
  "/api/v1/courses/{courseId}/channels/{channelId}/threads": {
    /**
     * スレッド一覧取得（ルートメッセージのみ）
     * @description threads_only対応
     */
    get: operations["API_065"];
    /**
     * スレッド作成（ルート投稿）
     * @description threadId=NULLで作成
     */
    post: operations["API_066"];
  };
  "/api/v1/courses/{courseId}/channels/{channelId}/threads/{threadId}/messages": {
    /**
     * スレッド内メッセージ一覧（ルート+返信）
     * @description threadId指定で返信も取得
     */
    get: operations["API_067"];
    /**
     * スレッド返信
     * @description threadId必須
     */
    post: operations["API_068"];
  };
  "/api/v1/payments/webhook": {
    /**
     * Stripe Webhook
     * @description 外部決済完了通知を受け取り、Enrollmentを自動的にactive化する。
     */
    post: operations["API_083"];
  };
  "/api/v1/health": {
    /**
     * ヘルスチェック
     * @description サーバーの死活監視用。DB、Redis、外部サービスの接続確認。
     */
    get: operations["API_084"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      id: string;
      email?: string | null;
      name?: string | null;
      isActive: boolean;
      /** Format: date-time */
      deletedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** @enum {unknown} */
      globalRole: components["schemas"]["GlobalRole"];
    };
    UserCreateRequest: {
      email?: string;
      name?: string;
      isActive?: boolean;
      /** Format: date-time */
      deletedAt?: string;
    };
    UserUpdateRequest: {
      email?: string;
      name?: string;
      isActive?: boolean;
      /** Format: date-time */
      deletedAt?: string;
    };
    PlatformMembership: {
      id: string;
      userId: string;
      /** @enum {string} */
      role: "operator" | "root_operator";
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    PlatformMembershipCreateRequest: {
      userId: string;
      /** @enum {string} */
      role: "operator" | "root_operator";
    };
    PlatformMembershipUpdateRequest: {
      userId?: string;
      /** @enum {string} */
      role?: "operator" | "root_operator";
    };
    Course: {
      id: string;
      title: string;
      description?: string | null;
      ownerUserId: string;
      /** @enum {string} */
      catalogVisibility: "public_listed" | "public_unlisted" | "private";
      /** @enum {string} */
      visibility: "public" | "instructors_only";
      isFrozen: boolean;
      /** Format: date-time */
      frozenAt?: string | null;
      frozenByUserId?: string | null;
      freezeReason?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** @description 作成者ユーザーID（instructor 作成 or operator/root 作成） */
      createdByUserId: string;
      /**
       * @description 講座ステータス
       * @enum {string}
       */
      status: "draft" | "pending_approval" | "active" | "archived";
      /** Format: date-time */
      approvalRequestedAt?: string | null;
      /** Format: date-time */
      approvedAt?: string | null;
      approvedByUserId?: string | null;
    };
    CourseCreateRequest: {
      title: string;
      description?: string;
      /** @deprecated */
      ownerUserId?: string;
      /** @enum {string} */
      catalogVisibility?: "public_listed" | "public_unlisted" | "private";
      /** @enum {string} */
      visibility?: "public" | "instructors_only";
      isFrozen?: boolean;
      /** Format: date-time */
      frozenAt?: string;
      frozenByUserId?: string;
      freezeReason?: string;
    };
    CourseUpdateRequest: {
      title?: string;
      description?: string;
      ownerUserId?: string;
      /** @enum {string} */
      catalogVisibility?: "public_listed" | "public_unlisted" | "private";
      /** @enum {string} */
      visibility?: "public" | "instructors_only";
      isFrozen?: boolean;
      /** Format: date-time */
      frozenAt?: string;
      frozenByUserId?: string;
      freezeReason?: string;
    };
    CourseMember: {
      id: string;
      courseId: string;
      userId: string;
      /** @enum {string} */
      role: "instructor_owner" | "learner" | "instructor" | "assistant";
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseMemberCreateRequest: {
      courseId: string;
      userId: string;
      /** @enum {string} */
      role: "instructor_owner" | "learner" | "instructor" | "assistant";
    };
    CourseMemberUpdateRequest: {
      courseId?: string;
      userId?: string;
      /** @enum {string} */
      role?: "instructor_owner" | "learner" | "instructor" | "assistant";
    };
    Lesson: {
      id: string;
      courseId: string;
      /** @enum {string} */
      type: "text" | "video" | "live" | "assignment";
      title: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    LessonCreateRequest: {
      courseId: string;
      /** @enum {string} */
      type: "text" | "video" | "live" | "assignment";
      title: string;
    };
    LessonUpdateRequest: {
      courseId?: string;
      /** @enum {string} */
      type?: "text" | "video" | "live" | "assignment";
      title?: string;
    };
    Assignment: {
      id: string;
      courseId: string;
      title: string;
      description?: string | null;
      /** Format: date-time */
      dueAt?: string | null;
      allowResubmission: boolean;
      isPublished: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    AssignmentCreateRequest: {
      courseId: string;
      title: string;
      description?: string;
      /** Format: date-time */
      dueAt?: string;
      allowResubmission?: boolean;
      isPublished?: boolean;
    };
    AssignmentUpdateRequest: {
      courseId?: string;
      title?: string;
      description?: string;
      /** Format: date-time */
      dueAt?: string;
      allowResubmission?: boolean;
      isPublished?: boolean;
    };
    CourseChannel: {
      id: string;
      courseId: string;
      /** @enum {string} */
      type: "assignment" | "one_on_one" | "announcement" | "general";
      /** @enum {string} */
      postingMode: "mixed" | "threads_only";
      /** @enum {string} */
      visibility: "public" | "instructors_only";
      isFrozen: boolean;
      /** Format: date-time */
      frozenAt?: string | null;
      frozenByUserId?: string | null;
      freezeReason?: string | null;
      name?: string | null;
      isManual: boolean;
      systemKey?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseChannelCreateRequest: {
      courseId: string;
      /** @enum {string} */
      type: "assignment" | "one_on_one" | "announcement" | "general";
      /** @enum {string} */
      postingMode?: "mixed" | "threads_only";
      /** @enum {string} */
      visibility?: "public" | "instructors_only";
      isFrozen?: boolean;
      /** Format: date-time */
      frozenAt?: string;
      frozenByUserId?: string;
      freezeReason?: string;
      name?: string;
      isManual?: boolean;
      systemKey?: string;
    };
    CourseChannelUpdateRequest: {
      courseId?: string;
      /** @enum {string} */
      type?: "assignment" | "one_on_one" | "announcement" | "general";
      /** @enum {string} */
      postingMode?: "mixed" | "threads_only";
      /** @enum {string} */
      visibility?: "public" | "instructors_only";
      isFrozen?: boolean;
      /** Format: date-time */
      frozenAt?: string;
      frozenByUserId?: string;
      freezeReason?: string;
      name?: string;
      isManual?: boolean;
      systemKey?: string;
    };
    CourseChannelMember: {
      id: string;
      channelId: string;
      courseMemberId: string;
      /** @enum {string} */
      status: "invited" | "joined" | "declined";
      /** Format: date-time */
      invitedAt?: string | null;
      /** Format: date-time */
      joinedAt?: string | null;
      /** Format: date-time */
      declinedAt?: string | null;
      lastReadMessageId?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseChannelMemberCreateRequest: {
      channelId: string;
      courseMemberId: string;
      /** @enum {string} */
      status?: "invited" | "joined" | "declined";
      /** Format: date-time */
      invitedAt?: string;
      /** Format: date-time */
      joinedAt?: string;
      /** Format: date-time */
      declinedAt?: string;
      lastReadMessageId?: string;
    };
    CourseChannelMemberUpdateRequest: {
      channelId?: string;
      courseMemberId?: string;
      /** @enum {string} */
      status?: "invited" | "joined" | "declined";
      /** Format: date-time */
      invitedAt?: string;
      /** Format: date-time */
      joinedAt?: string;
      /** Format: date-time */
      declinedAt?: string;
      lastReadMessageId?: string;
    };
    CourseThread: {
      id: string;
      channelId: string;
      /** @enum {string} */
      type: "submission" | "message_thread";
      rootMessageId?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseThreadCreateRequest: {
      channelId: string;
      /** @enum {string} */
      type: "submission" | "message_thread";
      rootMessageId?: string;
    };
    CourseThreadUpdateRequest: {
      channelId?: string;
      /** @enum {string} */
      type?: "submission" | "message_thread";
      rootMessageId?: string;
    };
    CourseThreadReadState: {
      id: string;
      threadId: string;
      courseMemberId: string;
      lastReadMessageId?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseThreadReadStateCreateRequest: {
      threadId: string;
      courseMemberId: string;
      lastReadMessageId?: string;
    };
    CourseThreadReadStateUpdateRequest: {
      threadId?: string;
      courseMemberId?: string;
      lastReadMessageId?: string;
    };
    CourseMessage: {
      id: string;
      channelId: string;
      threadId?: string | null;
      authorCourseMemberId?: string | null;
      text: string;
      isEmergency: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseMessageCreateRequest: {
      channelId: string;
      threadId?: string;
      authorCourseMemberId?: string;
      text: string;
      isEmergency?: boolean;
    };
    CourseMessageUpdateRequest: {
      channelId?: string;
      threadId?: string;
      authorCourseMemberId?: string;
      text?: string;
      isEmergency?: boolean;
    };
    CourseMessageAttachment: {
      id: string;
      courseMessageId: string;
      type: string;
      storageKey: string;
      fileName: string;
      mimeType: string;
      /** Format: int32 */
      size: number;
      /** Format: date-time */
      createdAt: string;
    };
    CourseMessageAttachmentCreateRequest: {
      courseMessageId: string;
      type: string;
      storageKey: string;
      fileName: string;
      mimeType: string;
      /** Format: int32 */
      size: number;
    };
    CourseMessageAttachmentUpdateRequest: {
      courseMessageId?: string;
      type?: string;
      storageKey?: string;
      fileName?: string;
      mimeType?: string;
      /** Format: int32 */
      size?: number;
    };
    CourseNotificationPreference: {
      id: string;
      courseMemberId: string;
      announcementNormalEnabled: boolean;
      submissionEnabled: boolean;
      submissionCommentEnabled: boolean;
      threadReplyEnabled: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseNotificationPreferenceCreateRequest: {
      courseMemberId: string;
      announcementNormalEnabled?: boolean;
      submissionEnabled?: boolean;
      submissionCommentEnabled?: boolean;
      threadReplyEnabled?: boolean;
    };
    CourseNotificationPreferenceUpdateRequest: {
      courseMemberId?: string;
      announcementNormalEnabled?: boolean;
      submissionEnabled?: boolean;
      submissionCommentEnabled?: boolean;
      threadReplyEnabled?: boolean;
    };
    CourseChannelNotificationPreference: {
      id: string;
      courseMemberId: string;
      channelId: string;
      muted: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseChannelNotificationPreferenceCreateRequest: {
      courseMemberId: string;
      channelId: string;
      muted?: boolean;
    };
    CourseChannelNotificationPreferenceUpdateRequest: {
      courseMemberId?: string;
      channelId?: string;
      muted?: boolean;
    };
    CourseEnrollment: {
      id: string;
      courseId: string;
      userId: string;
      /** @enum {string} */
      status: "applied" | "active" | "revoked";
      /** Format: date-time */
      grantedAt?: string | null;
      /** Format: date-time */
      revokedAt?: string | null;
      /** Format: date-time */
      paidAt?: string | null;
      /** @enum {string} */
      source: "stripe" | "manual";
      paymentId?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseEnrollmentCreateRequest: {
      courseId: string;
      userId: string;
      /** @enum {string} */
      status?: "applied" | "active" | "revoked";
      /** Format: date-time */
      grantedAt?: string;
      /** Format: date-time */
      revokedAt?: string;
      /** Format: date-time */
      paidAt?: string;
      /** @enum {string} */
      source?: "stripe" | "manual";
      paymentId?: string;
    };
    CourseEnrollmentUpdateRequest: {
      courseId?: string;
      userId?: string;
      /** @enum {string} */
      status?: "applied" | "active" | "revoked";
      /** Format: date-time */
      grantedAt?: string;
      /** Format: date-time */
      revokedAt?: string;
      /** Format: date-time */
      paidAt?: string;
      /** @enum {string} */
      source?: "stripe" | "manual";
      paymentId?: string;
    };
    Payment: {
      id: string;
      /** @enum {string} */
      provider: "stripe" | "manual";
      providerRef?: string | null;
      userId: string;
      courseId?: string | null;
      /** Format: int32 */
      amount: number;
      currency: string;
      /** @enum {string} */
      status: "pending" | "succeeded" | "failed" | "canceled" | "refunded";
      /** Format: date-time */
      paidAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    PaymentCreateRequest: {
      /** @enum {string} */
      provider?: "stripe" | "manual";
      providerRef?: string;
      userId: string;
      courseId?: string;
      /** Format: int32 */
      amount: number;
      currency?: string;
      /** @enum {string} */
      status?: "pending" | "succeeded" | "failed" | "canceled" | "refunded";
      /** Format: date-time */
      paidAt?: string;
    };
    PaymentUpdateRequest: {
      /** @enum {string} */
      provider?: "stripe" | "manual";
      providerRef?: string;
      userId?: string;
      courseId?: string;
      /** Format: int32 */
      amount?: number;
      currency?: string;
      /** @enum {string} */
      status?: "pending" | "succeeded" | "failed" | "canceled" | "refunded";
      /** Format: date-time */
      paidAt?: string;
    };
    Refund: {
      id: string;
      paymentId: string;
      providerRef?: string | null;
      /** Format: int32 */
      amount: number;
      /** @enum {string} */
      status: "pending" | "succeeded" | "failed" | "canceled";
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    RefundCreateRequest: {
      paymentId: string;
      providerRef?: string;
      /** Format: int32 */
      amount: number;
      /** @enum {string} */
      status?: "pending" | "succeeded" | "failed" | "canceled";
    };
    RefundUpdateRequest: {
      paymentId?: string;
      providerRef?: string;
      /** Format: int32 */
      amount?: number;
      /** @enum {string} */
      status?: "pending" | "succeeded" | "failed" | "canceled";
    };
    Coupon: {
      id: string;
      code: string;
      /** @enum {string} */
      discountType: "amount_fixed" | "amount_percent";
      /** Format: int32 */
      discountValue: number;
      currency?: string | null;
      /** Format: date-time */
      expiresAt?: string | null;
      /** Format: int32 */
      usageLimit?: number | null;
      /** Format: int32 */
      usedCount: number;
      isActive: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CouponCreateRequest: {
      code: string;
      /** @enum {string} */
      discountType: "amount_fixed" | "amount_percent";
      /** Format: int32 */
      discountValue: number;
      currency?: string;
      /** Format: date-time */
      expiresAt?: string;
      /** Format: int32 */
      usageLimit?: number;
      /** Format: int32 */
      usedCount?: number;
      isActive?: boolean;
    };
    CouponUpdateRequest: {
      code?: string;
      /** @enum {string} */
      discountType?: "amount_fixed" | "amount_percent";
      /** Format: int32 */
      discountValue?: number;
      currency?: string;
      /** Format: date-time */
      expiresAt?: string;
      /** Format: int32 */
      usageLimit?: number;
      /** Format: int32 */
      usedCount?: number;
      isActive?: boolean;
    };
    CouponRedemption: {
      id: string;
      couponId: string;
      userId: string;
      courseId?: string | null;
      paymentId?: string | null;
      /** Format: date-time */
      redeemedAt: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CouponRedemptionCreateRequest: {
      couponId: string;
      userId: string;
      courseId?: string;
      paymentId?: string;
      /** Format: date-time */
      redeemedAt?: string;
    };
    CouponRedemptionUpdateRequest: {
      couponId?: string;
      userId?: string;
      courseId?: string;
      paymentId?: string;
      /** Format: date-time */
      redeemedAt?: string;
    };
    AuditEvent: {
      id: string;
      /** Format: date-time */
      occurredAt: string;
      actorUserId: string;
      /** @enum {string} */
      actorGlobalRole: "guest" | "learner" | "instructor" | "assistant" | "operator" | "root_operator";
      /** @enum {string} */
      eventType: components["schemas"]["AuditEventType"];
      courseId?: string | null;
      channelId?: string | null;
      messageId?: string | null;
      reason: string;
      metaJson?: Record<string, unknown> | null;
      requestId?: string | null;
      ipHash?: string | null;
      userAgentHash?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    AuditEventCreateRequest: {
      /** Format: date-time */
      occurredAt?: string;
      actorUserId: string;
      /** @enum {string} */
      actorGlobalRole: "guest" | "learner" | "instructor" | "assistant" | "operator" | "root_operator";
      /** @enum {string} */
      eventType: "announcement_emergency_posted" | "course_frozen" | "course_unfrozen" | "channel_frozen" | "channel_unfrozen" | "dm_viewed_by_root_operator" | "course_created" | "course_approval_requested" | "course_approved" | "course_published" | "course_member_role_promoted";
      courseId?: string;
      channelId?: string;
      messageId?: string;
      reason: string;
      metaJson?: Record<string, never>;
      requestId?: string;
      ipHash?: string;
      userAgentHash?: string;
    };
    AuditEventUpdateRequest: {
      /** Format: date-time */
      occurredAt?: string;
      actorUserId?: string;
      /** @enum {string} */
      actorGlobalRole?: "guest" | "learner" | "instructor" | "assistant" | "operator" | "root_operator";
      /** @enum {string} */
      eventType?: "announcement_emergency_posted" | "course_frozen" | "course_unfrozen" | "channel_frozen" | "channel_unfrozen" | "dm_viewed_by_root_operator" | "course_created" | "course_approval_requested" | "course_approved" | "course_published" | "course_member_role_promoted";
      courseId?: string;
      channelId?: string;
      messageId?: string;
      reason?: string;
      metaJson?: Record<string, never>;
      requestId?: string;
      ipHash?: string;
      userAgentHash?: string;
    };
    Order: {
      id: string;
      userId: string;
      courseId: string;
      /** Format: int32 */
      amount: number;
      currency: string;
      /** @enum {unknown} */
      status: components["schemas"]["OrderStatus"];
      paymentProvider: string;
      paymentIntentId?: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    OrderCreateRequest: {
      userId: string;
      courseId: string;
      /** Format: int32 */
      amount: number;
      currency: string;
      /** @enum {string} */
      status: "pending" | "paid" | "cancelled" | "failed" | "refunded";
      paymentProvider: string;
      paymentIntentId?: string;
    };
    OrderUpdateRequest: {
      userId?: string;
      courseId?: string;
      /** Format: int32 */
      amount?: number;
      currency?: string;
      /** @enum {string} */
      status?: "pending" | "paid" | "cancelled" | "failed" | "refunded";
      paymentProvider?: string;
      paymentIntentId?: string;
    };
    OAuthIdentity: {
      id: string;
      userId: string;
      provider: string;
      providerUserId: string;
      email?: string | null;
      /** Format: date-time */
      lastLoginAt?: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    OAuthIdentityCreateRequest: {
      userId: string;
      provider: string;
      providerUserId: string;
      email?: string;
      /** Format: date-time */
      lastLoginAt?: string;
    };
    OAuthIdentityUpdateRequest: {
      userId?: string;
      provider?: string;
      providerUserId?: string;
      email?: string;
      /** Format: date-time */
      lastLoginAt?: string;
    };
    PasswordCredential: {
      id: string;
      userId: string;
      passwordHash: string;
      algorithm: string;
      /** Format: date-time */
      passwordUpdatedAt: string;
      isDisabled: boolean;
      /** Format: int32 */
      failedCount: number;
      /** Format: date-time */
      lastFailedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    PasswordCredentialCreateRequest: {
      userId: string;
      passwordHash: string;
      algorithm: string;
      /** Format: date-time */
      passwordUpdatedAt: string;
      isDisabled?: boolean;
      /** Format: int32 */
      failedCount?: number;
      /** Format: date-time */
      lastFailedAt?: string;
    };
    PasswordCredentialUpdateRequest: {
      userId?: string;
      passwordHash?: string;
      algorithm?: string;
      /** Format: date-time */
      passwordUpdatedAt?: string;
      isDisabled?: boolean;
      /** Format: int32 */
      failedCount?: number;
      /** Format: date-time */
      lastFailedAt?: string;
    };
    FileObject: {
      id: string;
      storageKey: string;
      bucket: string;
      fileName: string;
      mimeType: string;
      /** Format: int32 */
      size: number;
      checksum?: string | null;
      isScanned: boolean;
      isMalicious: boolean;
      createdByUserId?: string | null;
      /** Format: date-time */
      deletedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    FileObjectCreateRequest: {
      storageKey: string;
      bucket: string;
      fileName: string;
      mimeType: string;
      /** Format: int32 */
      size: number;
      checksum?: string;
      isScanned?: boolean;
      isMalicious?: boolean;
      createdByUserId?: string;
      /** Format: date-time */
      deletedAt?: string;
    };
    FileObjectUpdateRequest: {
      storageKey?: string;
      bucket?: string;
      fileName?: string;
      mimeType?: string;
      /** Format: int32 */
      size?: number;
      checksum?: string;
      isScanned?: boolean;
      isMalicious?: boolean;
      createdByUserId?: string;
      /** Format: date-time */
      deletedAt?: string;
    };
    Submission: {
      id: string;
      assignmentId: string;
      courseId: string;
      userId: string;
      threadId: string;
      /** Format: date-time */
      submittedAt: string;
      /** @enum {unknown} */
      status: components["schemas"]["SubmissionStatus"];
      /** Format: date-time */
      gradedAt?: string | null;
    };
    SubmissionCreateRequest: {
      assignmentId: string;
      courseId: string;
      userId: string;
      threadId: string;
      /** Format: date-time */
      submittedAt?: string;
      /** @enum {string} */
      status: "draft" | "submitted" | "returned" | "graded";
      /** Format: date-time */
      gradedAt?: string;
    };
    SubmissionUpdateRequest: {
      assignmentId?: string;
      courseId?: string;
      userId?: string;
      threadId?: string;
      /** Format: date-time */
      submittedAt?: string;
      /** @enum {string} */
      status?: "draft" | "submitted" | "returned" | "graded";
      /** Format: date-time */
      gradedAt?: string;
    };
    UserProfile: {
      id: string;
      userId: string;
      displayName: string;
      avatarFileObjectId?: string | null;
      bio?: string | null;
      isPublic: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UserProfileCreateRequest: {
      userId: string;
      displayName: string;
      avatarFileObjectId?: string;
      bio?: string;
      isPublic?: boolean;
    };
    UserProfileUpdateRequest: {
      userId?: string;
      displayName?: string;
      avatarFileObjectId?: string;
      bio?: string;
      isPublic?: boolean;
    };
    GradingComment: {
      id: string;
      courseId: string;
      threadId: string;
      authorUserId: string;
      targetUserId: string;
      body: string;
      /** Format: int32 */
      score?: number | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    GradingCommentCreateRequest: {
      courseId: string;
      threadId: string;
      authorUserId: string;
      targetUserId: string;
      body: string;
      /** Format: int32 */
      score?: number;
    };
    GradingCommentUpdateRequest: {
      courseId?: string;
      threadId?: string;
      authorUserId?: string;
      targetUserId?: string;
      body?: string;
      /** Format: int32 */
      score?: number;
    };
    SuccessResponse: {
      success: boolean;
    };
    ErrorResponse: {
      message: string;
      code?: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    LoginResponse: {
      accessToken: string;
      refreshToken: string;
    };
    RegisterRequest: {
      /** Format: email */
      email: string;
      password: string;
      name: string;
    };
    RegisterResponse: components["schemas"]["User"];
    RefreshResponse: {
      accessToken: string;
    };
    CheckoutRequest: {
      courseId: string;
      couponCode?: string;
    };
    CheckoutResponse: {
      sessionId: string;
      /** Format: uri */
      url: string;
    };
    Notification: {
      id: string;
      type: string;
      title: string;
      body?: string;
      isRead: boolean;
      /** Format: date-time */
      createdAt: string;
    };
    NotificationListResponse: {
      items: components["schemas"]["Notification"][];
    };
    CourseSideMenuResponse: {
      items: Record<string, never>[];
    };
    CursorPageInfo: {
      nextCursor?: string | null;
      hasMore: boolean;
    };
    OffsetPageInfo: {
      page: number;
      pageSize: number;
      total?: number | null;
    };
    ListMeta: {
      page?: components["schemas"]["OffsetPageInfo"];
      cursor?: components["schemas"]["CursorPageInfo"];
    };
    UserPublicView: {
      id: string;
      displayName: string;
      avatarUrl?: string | null;
    };
    FileObjectView: {
      file: components["schemas"]["FileObject"];
      url: string;
      mimeType?: string | null;
      size?: number | null;
    };
    MessageReactionView: {
      emoji: string;
      count: number;
      reactedByMe: boolean;
    };
    CourseMessageView: {
      message: components["schemas"]["CourseMessage"];
      sender: components["schemas"]["UserPublicView"];
      attachments: components["schemas"]["FileObjectView"][];
      reactions: components["schemas"]["MessageReactionView"][];
    };
    CourseChannelSummaryView: {
      channel: components["schemas"]["CourseChannel"];
      /** Format: date-time */
      lastMessageAt?: string | null;
      unreadCount: number;
    };
    CourseStatsView: {
      learnerCount: number;
      assignmentCount: number;
      lessonCount: number;
      activeChannelCount: number;
    };
    CourseSummaryView: {
      course: components["schemas"]["Course"];
      channelCount: number;
      memberCount: number;
      isFrozen: boolean;
    };
    CourseDetailView: {
      course: components["schemas"]["Course"];
      channels: components["schemas"]["CourseChannelSummaryView"][];
      stats: components["schemas"]["CourseStatsView"];
    };
    ThreadSummaryView: {
      threadId: string;
      rootMessage: components["schemas"]["CourseMessageView"];
      replyCount: number;
      /** Format: date-time */
      lastReplyAt?: string | null;
    };
    AssignmentSummaryView: {
      assignment: components["schemas"]["Assignment"];
      /** Format: date-time */
      dueAt?: string | null;
      status: string;
    };
    AssignmentDetailView: {
      assignment: components["schemas"]["Assignment"];
      mySubmission?: components["schemas"]["Submission"];
      rubric?: {
        [key: string]: unknown;
      } | null;
    };
    SubmissionView: {
      submission: components["schemas"]["Submission"];
      attachments: components["schemas"]["FileObjectView"][];
    };
    PaymentSummaryView: {
      payment: components["schemas"]["Payment"];
      course: components["schemas"]["Course"];
      buyer: components["schemas"]["UserPublicView"];
    };
    CourseListResponse: {
      items: components["schemas"]["CourseSummaryView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    CourseChannelListResponse: {
      items: components["schemas"]["CourseChannelSummaryView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    ThreadListResponse: {
      items: components["schemas"]["ThreadSummaryView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    MessageListResponse: {
      items: components["schemas"]["CourseMessageView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    AssignmentListResponse: {
      items: components["schemas"]["AssignmentSummaryView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    PaymentListResponse: {
      items: components["schemas"]["PaymentSummaryView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    GenericWriteRequest: {
      [key: string]: unknown;
    };
    GenericDetailView: {
      [key: string]: unknown;
    };
    GenericListResponse: {
      items: Record<string, never>[];
      meta?: components["schemas"]["ListMeta"];
    };
    OperatorAdminView: {
      [key: string]: unknown;
    };
    OperatorListResponse: {
      items: components["schemas"]["OperatorAdminView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    UserMeView: components["schemas"]["User"];
    CourseChannelDetailView: components["schemas"]["CourseChannel"];
    InstructorCourseCreateRequest: {
      title: string;
      description?: string;
      /** @enum {string} */
      catalogVisibility?: "public_listed" | "public_unlisted" | "private";
      /** @enum {string} */
      visibility?: "public" | "instructors_only";
    };
    /** @enum {string} */
    GlobalRole: "guest" | "learner" | "instructor" | "assistant" | "operator" | "root_operator";
    /** @enum {string} */
    OrderStatus: "pending" | "paid" | "cancelled" | "failed" | "refunded";
    /** @enum {string} */
    SubmissionStatus: "draft" | "submitted" | "returned" | "graded";
    /** @enum {string} */
    AuditEventType: "announcement_emergency_posted" | "course_frozen" | "course_unfrozen" | "channel_frozen" | "channel_unfrozen" | "dm_viewed_by_root_operator" | "course_created" | "course_approval_requested" | "course_approved" | "course_published" | "course_member_role_promoted";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * プロフィール取得
   * @description ログイン中ユーザー自身の基本情報（名前、アイコン、全体ロール、所属組織等）を取得する。
   */
  API_007: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["UserMeView"];
        };
      };
    };
  };
  /**
   * プロフィール更新
   * @description 名前、アイコン画像URL、自己紹介等のプロフィール情報を更新する（image_33b70dのデザインを反映）。
   */
  API_008: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * PW変更
   * @description 現在のパスワードを検証した上で、新しいパスワードへ直接変更する。セキュリティ上、即時反映される。
   */
  API_009: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * 通知一覧取得
   * @description 自分宛の通知（返信、採点完了、ライブ予約、運営案内）を最新順に取得する（image_32dc7bのリスト用）。
   */
  API_010: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * 通知既読化
   * @description 指定されたIDの通知を既読状態にする。UI上のバッジカウントを減らすトリガーとなる。
   */
  API_011: {
    parameters: {
      path: {
        notificationId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * 通知一括既読
   * @description 全ての未読通知を一括で既読状態にする。
   */
  API_012: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * 通知設定取得
   * @description メール通知、プッシュ通知のON/OFF、およびカテゴリ別の受け取り設定を取得する。
   */
  API_013: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * 通知設定更新
   * @description 通知設定をユーザーの好みに合わせて更新する。
   */
  API_014: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * 講座一覧取得
   * @description 公開中(active)の講座を検索・取得。1on1、セミナー、ブートキャンプのスタイルやカテゴリでフィルタが可能。
   */
  API_015: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseListResponse"];
        };
      };
    };
  };
  /**
   * 講座詳細取得
   * @description 未受講者向けLPデータ。アウトカム、前提条件、おすすめ、FAQ、日程スケジュールをすべて取得。
   */
  API_016: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericDetailView"];
        };
      };
    };
  };
  /**
   * 講座申込(開始)
   * @description 講座への受講を申し込む。有料時はpending、無料時はactiveでEnrollmentを生成する。
   */
  API_017: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * Stripeセッション生成
   * @description 有料講座の決済を開始するためのStripe URLを発行。コースがfrozen時は423でブロック。
   */
  API_018: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckoutRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CheckoutResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * マイ講座一覧
   * @description 自身が受講中、または過去に受講したすべての講座をリスト取得する。
   */
  API_019: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * 受講中講座詳細
   * @description 受講者用学習画面。最新の進捗、シラバス、受講者専用の連絡事項、解禁済み教材等を取得。
   */
  API_020: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 決済/申込状況確認
   * @description pending状態（決済確認中）からactiveになったかをポーリング/確認するためのAPI。
   */
  API_021: {
    parameters: {
      path: {
        enrollmentId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericDetailView"];
        };
      };
    };
  };
  /**
   * サイドメニュー取得
   * @description チャットチャンネルと解禁済み課題レッスンを階層構造化して取得（image_3345d2を完全再現）。
   */
  API_022: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * 自分の課題一覧
   * @description 自分が提出すべき、または提出済みのすべての課題を全講座横断で一覧取得する。
   */
  API_023: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AssignmentListResponse"];
        };
      };
    };
  };
  /**
   * 課題詳細取得
   * @description 課題の設問内容、配布資料、現在の提出状況と講師からの最新フィードバックを取得する。
   */
  API_024: {
    parameters: {
      path: {
        lessonId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AssignmentDetailView"];
        };
      };
    };
  };
  /**
   * 課題提出
   * @description 回答を提出。自動的にassignmentチャンネル内に講師との返信用スレッドを生成する。
   */
  API_025: {
    parameters: {
      path: {
        lessonId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["SubmissionView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 学習実績取得
   * @description 獲得した証明書、バッジ、修了した講座の最終成績や学習時間統計を一覧取得する。
   */
  API_026: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * カレンダー取得
   * @description 受講している全講座のライブ予定、提出期限、面談予定をカレンダー形式(JSON)で取得。
   */
  API_027: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * コース修了処理
   * @description 全レッスン完了時の最終修了申請。講師による最終確認が必要な場合、評価待ちへ遷移。
   */
  API_028: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * アンケート取得
   * @description 講座内アンケートの設問（選択式、記述式）を取得する。
   */
  API_029: {
    parameters: {
      path: {
        surveyId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericDetailView"];
        };
      };
    };
  };
  /**
   * アンケート回答
   * @description アンケート回答を送信。423チェック対象。回答により教材解禁が連動する場合がある。
   */
  API_030: {
    parameters: {
      path: {
        surveyId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 自講座一覧
   * @description 自分が管理、または講師として参加（担当）している全講座を一覧取得する。
   */
  API_031: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseListResponse"];
        };
      };
    };
  };
  /**
   * 講座新規作成（講師）
   * @description 講師がコースを新規作成。ownerUserId=作成者（サーバー側で自動設定、リクエストでの指定不可）。初期status=draft。CourseMember(role=instructor_owner)が自動作成される。公開にはrequest-approval→approve が必要。
   */
  API_032: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InstructorCourseCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * 講座詳細取得(管理)
   * @description 講師用管理画面。売上概況、受講者推移、下書き情報を含む管理用詳細データ。
   */
  API_033: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * 講座情報更新
   * @description 講座のタイトル、LP、価格、募集期間、マーケティング項目を更新（image_33637a反映）。
   */
  API_034: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CourseUpdateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 講座削除(論理)
   * @description 講座を論理削除(archived)状態にする。既存の受講生には閲覧権限のみ残存させる。
   */
  API_035: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * 承認申請
   * @description 運営へ公開審査を依頼。statusがpending_approvalとなり、以降承認まで423 Locked。
   */
  API_036: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * コース公開（講師）
   * @description ownerUserId一致の講師がコースを公開する。statusをactiveに変更。operator作成コースの場合、CourseMember.roleをinstructor→instructor_ownerへ昇格（委譲完了）。
   */
  API_036B: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Forbidden (ownerUserId不一致) */
      403: {
        content: never;
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 売上分析サマリ
   * @description 期間別の収益、成約率、受講生離脱ポイント等の分析サマリーを取得。
   */
  API_037: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * 振込先銀行設定
   * @description 講師への報酬振込先口座情報をStripe Connect等と連携して設定・更新。
   */
  API_038: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * シラバス構造取得
   * @description 編集中の章立てとレッスン構成をツリー形式で取得（image_32dd18の構成用）。
   */
  API_039: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * セクション追加
   * @description カリキュラム内に新しい「章」を追加。423チェック対象。
   */
  API_040: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * セクション編集
   * @description セクション名の変更、表示順の並び替え、および削除。
   */
  API_041: {
    parameters: {
      path: {
        sectionId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * セクション削除
   * @description 指定されたセクションと、配下のレッスン紐付けを削除（論理/物理）。
   */
  API_042: {
    parameters: {
      path: {
        sectionId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * レッスン作成
   * @description 指定セクションに新規レッスンを追加（座学/動画/課題/ライブ）（image_32dcf8反映）。
   */
  API_043: {
    parameters: {
      path: {
        sectionId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * レッスン詳細取得
   * @description 編集画面用。動画URL、リッチテキスト本文、課題要件、Drip設定の詳細。
   */
  API_044: {
    parameters: {
      path: {
        lessonId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericDetailView"];
        };
      };
    };
  };
  /**
   * レッスン編集
   * @description コンテンツの修正、Drip(解禁日)、先行ロック条件の保存。423チェック対象。
   */
  API_045: {
    parameters: {
      path: {
        lessonId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * レッスン削除
   * @description レッスンをカリキュラムから削除。
   */
  API_046: {
    parameters: {
      path: {
        lessonId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * ライブ配信設定
   * @description ZoomやYouTube LiveのURL、および配信日時の設定（カレンダー連動）。
   */
  API_047: {
    parameters: {
      path: {
        lessonId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 提出一覧取得
   * @description 受講者別の課題進捗、未確認提出物、最終提出日時の一覧（image_32dcd7反映）。
   */
  API_048: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * 評価・採点実行
   * @description 提出物への合否、講評を送信。合格時は自動で次の教材を解禁。フィードバックはスレッドへ。
   */
  API_049: {
    parameters: {
      path: {
        submissionId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SubmissionView"];
        };
      };
    };
  };
  /**
   * 受講者名簿取得
   * @description 全参加ユーザーの属性、現在の進捗状況、メールアドレス等の名簿取得。
   */
  API_050: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * 講座内ロール変更
   * @description 特定ユーザーの役割（講師、アシスタント、受講生）を動的に切り替え。
   */
  API_051: {
    parameters: {
      path: {
        courseId: string;
        userId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 受講権限剥奪
   * @description 特定ユーザーの受講権限を剥奪（revoked）し、コンテンツへのアクセスを遮断。
   */
  API_052: {
    parameters: {
      path: {
        courseId: string;
        userId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 受講者CSV出力
   * @description 受講者名簿と学習進捗データをCSV形式でエクスポートする。
   */
  API_053: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * チャンネル一覧取得
   * @description サイドメニュー構築用。general, announcement等のチャンネル種別を含む。
   */
  API_054: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseChannelListResponse"];
        };
      };
    };
  };
  /**
   * チャンネル作成
   * @description コース内に新しいカスタムチャンネルを追加。
   */
  API_055: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CourseChannelCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * チャンネル編集
   * @description チャンネル名、説明文、閲覧制限、アーカイブ状態の更新。
   */
  API_056: {
    parameters: {
      path: {
        channelId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseChannelDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * チャンネル削除
   * @description チャンネルを論理削除。過去ログは監査用に保持。
   */
  API_057: {
    parameters: {
      path: {
        channelId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * メッセージ履歴取得
   * @description スレッド親（ルート）メッセージの一覧取得。課題の相互閲覧可（image_32d9b1反映）。
   */
  API_058: {
    parameters: {
      path: {
        channelId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["MessageListResponse"];
        };
      };
    };
  };
  /**
   * メッセージ投稿
   * @description チャンネルへの新規投稿。親メッセージとして保存。threads_onlyを強制適用。
   */
  API_059: {
    parameters: {
      path: {
        channelId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CourseMessageCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseChannelDetailView"];
        };
      };
    };
  };
  /**
   * スレッド詳細取得
   * @description 特定メッセージに紐づく返信メッセージ一覧（スレッドビュー）を全件取得。
   */
  API_060: {
    parameters: {
      path: {
        messageId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * スレッド返信投稿
   * @description 返信投稿(image_32d9b1)。announcementタイプは講師以外返信不可。
   */
  API_061: {
    parameters: {
      path: {
        messageId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseMessageView"];
        };
      };
    };
  };
  /**
   * メッセージ削除
   * @description 投稿の論理削除。返信がある場合は「削除されました」と表示。
   */
  API_063: {
    parameters: {
      path: {
        messageId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * メッセージ編集
   * @description 自分の投稿内容を修正。編集履歴を保持。423チェック対象。
   */
  API_062: {
    parameters: {
      path: {
        messageId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseMessageView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * リアクション追加
   * @description メッセージに対する絵文字リアクションの付与。423チェック対象。
   */
  API_064: {
    parameters: {
      path: {
        messageId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseMessageView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * スレッド一覧取得（ルートメッセージのみ）
   * @description threads_only対応
   */
  API_065: {
    parameters: {
      path: {
        courseId: string;
        channelId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ThreadListResponse"];
        };
      };
    };
  };
  /**
   * スレッド作成（ルート投稿）
   * @description threadId=NULLで作成
   */
  API_066: {
    parameters: {
      path: {
        courseId: string;
        channelId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * スレッド内メッセージ一覧（ルート+返信）
   * @description threadId指定で返信も取得
   */
  API_067: {
    parameters: {
      path: {
        courseId: string;
        channelId: string;
        threadId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["MessageListResponse"];
        };
      };
    };
  };
  /**
   * スレッド返信
   * @description threadId必須
   */
  API_068: {
    parameters: {
      path: {
        courseId: string;
        channelId: string;
        threadId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CourseMessageCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * Stripe Webhook
   * @description 外部決済完了通知を受け取り、Enrollmentを自動的にactive化する。
   */
  API_083: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * ヘルスチェック
   * @description サーバーの死活監視用。DB、Redis、外部サービスの接続確認。
   */
  API_084: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
}
