/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/users/me": {
    /**
     * プロフィール取得
     * @description ログイン中ユーザー自身の基本情報を取得する。
     */
    get: operations["API_001"];
    /**
     * プロフィール更新
     * @description プロフィール情報を更新する。
     */
    put: operations["API_002"];
  };
  "/api/v1/users/me/password": {
    /**
     * パスワード変更
     * @description パスワードを変更する。
     */
    put: operations["API_003"];
  };
  "/api/v1/notifications": {
    /**
     * 通知一覧取得
     * @description 自分宛の通知一覧を取得する。
     */
    get: operations["API_004"];
  };
  "/api/v1/notifications/{notificationId}/read": {
    /**
     * 通知既読化
     * @description 指定した通知を既読にする。
     */
    post: operations["API_005"];
  };
  "/api/v1/notifications/read-all": {
    /**
     * 通知一括既読
     * @description 全通知を一括既読にする。
     */
    post: operations["API_006"];
  };
  "/api/v1/users/me/settings/notifications": {
    /**
     * 通知設定取得
     * @description 通知設定を取得する。
     */
    get: operations["API_007"];
    /**
     * 通知設定更新
     * @description 通知設定を更新する。
     */
    put: operations["API_008"];
  };
  "/api/v1/store/courses": {
    /**
     * 講座一覧取得
     * @description ストア公開講座一覧を取得する。
     */
    get: operations["API_009"];
  };
  "/api/v1/store/courses/{courseId}": {
    /**
     * 講座詳細取得
     * @description 講座の詳細情報を取得する。
     */
    get: operations["API_010"];
  };
  "/api/v1/store/courses/{courseId}/apply": {
    /**
     * 講座申込(開始)
     * @description 講座への受講申込を開始する。
     */
    post: operations["API_011"];
  };
  "/api/v1/payments/stripe/checkout": {
    /**
     * Stripeセッション生成
     * @description Stripe Checkoutセッションを生成する。
     */
    post: operations["API_012"];
  };
  "/api/v1/learner/courses": {
    /**
     * マイ講座一覧
     * @description 受講中の講座一覧を取得する。
     */
    get: operations["API_013"];
  };
  "/api/v1/learner/courses/{courseId}": {
    /**
     * 受講中講座詳細
     * @description 受講中講座の詳細を取得する。
     */
    get: operations["API_014"];
  };
  "/api/v1/learner/enrollments/{enrollmentId}": {
    /**
     * 決済/申込状況確認
     * @description 受講申込・決済の状況を確認する。
     */
    get: operations["API_015"];
  };
  "/api/v1/learner/courses/{courseId}/side-menu": {
    /**
     * サイドメニュー取得
     * @description コース内サイドメニューを取得する。
     */
    get: operations["API_016"];
  };
  "/api/v1/learner/assignments": {
    /**
     * 自分の課題一覧
     * @description 自分の課題一覧を取得する。
     */
    get: operations["API_017"];
  };
  "/api/v1/learner/assignments/{lessonId}": {
    /**
     * 課題詳細取得
     * @description 課題の詳細情報を取得する。
     */
    get: operations["API_018"];
  };
  "/api/v1/learner/lessons/{lessonId}/submissions": {
    /**
     * 課題提出
     * @description 課題を提出する。
     */
    post: operations["API_019"];
  };
  "/api/v1/learner/records": {
    /**
     * 学習実績取得
     * @description 学習実績を取得する。
     */
    get: operations["API_020"];
  };
  "/api/v1/learner/calendar": {
    /**
     * カレンダー取得
     * @description カレンダー情報を取得する。
     */
    get: operations["API_021"];
  };
  "/api/v1/learner/courses/{courseId}/complete": {
    /**
     * コース修了処理
     * @description コースの修了を申請する。
     */
    post: operations["API_022"];
  };
  "/api/v1/surveys/{surveyId}": {
    /**
     * アンケート取得
     * @description アンケートを取得する。
     */
    get: operations["API_023"];
  };
  "/api/v1/surveys/{surveyId}/responses": {
    /**
     * アンケート回答
     * @description アンケートに回答する。
     */
    post: operations["API_024"];
  };
  "/api/v1/instructor/courses": {
    /**
     * 自講座一覧
     * @description 講師として管理する講座一覧を取得する。
     */
    get: operations["API_025"];
    /**
     * 講座新規作成（講師）
     * @description 講師がコースを新規作成する。
     */
    post: operations["API_026"];
  };
  "/api/v1/instructor/courses/{courseId}": {
    /**
     * 講座詳細取得(管理)
     * @description 講師管理用の講座詳細を取得する。
     */
    get: operations["API_027"];
    /**
     * 講座情報更新
     * @description 講座情報を更新する。
     */
    put: operations["API_028"];
    /**
     * 講座削除(論理)
     * @description 講座を論理削除する。
     */
    delete: operations["API_029"];
  };
  "/api/v1/instructor/courses/{courseId}/request-approval": {
    /**
     * 承認申請
     * @description 講座の公開承認を申請する。
     */
    post: operations["API_030"];
  };
  "/api/v1/instructor/courses/{courseId}/publish": {
    /**
     * コース公開（講師）
     * @description 承認済み講座を公開する。
     */
    post: operations["API_031"];
  };
  "/api/v1/instructor/analytics/overview": {
    /**
     * 売上分析サマリ
     * @description 売上分析サマリを取得する。
     */
    get: operations["API_032"];
  };
  "/api/v1/instructor/settings/payout": {
    /**
     * 振込先銀行設定
     * @description 振込先銀行口座を設定する。
     */
    put: operations["API_033"];
  };
  "/api/v1/instructor/courses/{courseId}/syllabus": {
    /**
     * シラバス構造取得
     * @description シラバス構造を取得する。
     */
    get: operations["API_034"];
  };
  "/api/v1/instructor/courses/{courseId}/sections": {
    /**
     * セクション追加
     * @description セクションを追加する。
     */
    post: operations["API_035"];
  };
  "/api/v1/instructor/sections/{sectionId}": {
    /**
     * セクション編集
     * @description セクションを編集する。
     */
    put: operations["API_036"];
    /**
     * セクション削除
     * @description セクションを削除する。
     */
    delete: operations["API_037"];
  };
  "/api/v1/instructor/sections/{sectionId}/lessons": {
    /**
     * レッスン作成
     * @description レッスンを作成する。
     */
    post: operations["API_038"];
  };
  "/api/v1/instructor/lessons/{lessonId}": {
    /**
     * レッスン詳細取得
     * @description レッスン詳細を取得する。
     */
    get: operations["API_039"];
    /**
     * レッスン編集
     * @description レッスンを編集する。
     */
    put: operations["API_040"];
    /**
     * レッスン削除
     * @description レッスンを削除する。
     */
    delete: operations["API_041"];
  };
  "/api/v1/instructor/lessons/{lessonId}/live": {
    /**
     * ライブ配信設定
     * @description ライブ配信設定を行う。
     */
    put: operations["API_042"];
  };
  "/api/v1/instructor/courses/{courseId}/submissions": {
    /**
     * 提出一覧取得
     * @description 提出物一覧を取得する。
     */
    get: operations["API_043"];
  };
  "/api/v1/instructor/submissions/{submissionId}/evaluation": {
    /**
     * 評価・採点実行
     * @description 提出物の評価・採点を実行する。
     */
    patch: operations["API_044"];
  };
  "/api/v1/instructor/courses/{courseId}/members": {
    /**
     * 受講者名簿取得
     * @description 受講者名簿を取得する。
     */
    get: operations["API_045"];
  };
  "/api/v1/instructor/courses/{courseId}/members/{userId}/role": {
    /**
     * 講座内ロール変更
     * @description コースメンバーのロールを変更する。
     */
    patch: operations["API_046"];
  };
  "/api/v1/instructor/courses/{courseId}/members/{userId}/revoke": {
    /**
     * 受講権限剥奪
     * @description 受講権限を剥奪する。
     */
    post: operations["API_047"];
  };
  "/api/v1/instructor/courses/{courseId}/export": {
    /**
     * 受講者CSV出力
     * @description 受講者一覧をCSVエクスポートする。
     */
    get: operations["API_048"];
  };
  "/api/v1/courses/{courseId}/channels": {
    /**
     * チャンネル一覧取得
     * @description チャンネル一覧を取得する。
     */
    get: operations["API_049"];
    /**
     * チャンネル作成
     * @description チャンネルを作成する。
     */
    post: operations["API_050"];
  };
  "/api/v1/channels/{channelId}": {
    /**
     * チャンネル編集
     * @description チャンネルを編集する。
     */
    put: operations["API_051"];
    /**
     * チャンネル削除
     * @description チャンネルを削除する。
     */
    delete: operations["API_052"];
  };
  "/api/v1/channels/{channelId}/messages": {
    /**
     * メッセージ履歴取得
     * @description メッセージ履歴を取得する。
     */
    get: operations["API_053"];
    /**
     * メッセージ投稿
     * @description メッセージを投稿する。
     */
    post: operations["API_054"];
  };
  "/api/v1/messages/{messageId}/thread": {
    /**
     * スレッド詳細取得
     * @description スレッド詳細を取得する。
     */
    get: operations["API_055"];
  };
  "/api/v1/messages/{messageId}/replies": {
    /**
     * スレッド返信投稿
     * @description スレッドに返信する。
     */
    post: operations["API_056"];
  };
  "/api/v1/messages/{messageId}": {
    /**
     * メッセージ削除
     * @description メッセージを削除する。
     */
    delete: operations["API_058"];
    /**
     * メッセージ編集
     * @description メッセージを編集する。
     */
    patch: operations["API_057"];
  };
  "/api/v1/messages/{messageId}/reactions": {
    /**
     * リアクション追加
     * @description リアクションを追加する。
     */
    post: operations["API_059"];
  };
  "/api/v1/courses/{courseId}/channels/{channelId}/threads": {
    /**
     * スレッド一覧取得
     * @description スレッド一覧を取得する。
     */
    get: operations["API_060"];
    /**
     * スレッド作成
     * @description スレッドを作成する。
     */
    post: operations["API_061"];
  };
  "/api/v1/courses/{courseId}/channels/{channelId}/threads/{threadId}/messages": {
    /**
     * スレッド内メッセージ一覧
     * @description スレッド内メッセージを取得する。
     */
    get: operations["API_062"];
    /**
     * スレッド返信
     * @description スレッドに返信する。
     */
    post: operations["API_063"];
  };
  "/api/v1/payments/webhook": {
    /**
     * Stripe Webhook
     * @description Stripe Webhookを受信する。
     */
    post: operations["API_064"];
  };
  "/api/v1/health": {
    /**
     * ヘルスチェック
     * @description サーバーの死活監視。
     */
    get: operations["API_065"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      id: string;
      email?: string | null;
      name?: string | null;
      isActive: boolean;
      /** Format: date-time */
      deletedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** @enum {unknown} */
      globalRole: components["schemas"]["GlobalRole"];
    };
    UserCreateRequest: {
      email?: string;
      name?: string;
      isActive?: boolean;
      /** Format: date-time */
      deletedAt?: string;
    };
    UserUpdateRequest: {
      email?: string;
      name?: string;
      isActive?: boolean;
      /** Format: date-time */
      deletedAt?: string;
    };
    Course: {
      id: string;
      title: string;
      description?: string | null;
      ownerUserId: string;
      /** @enum {string} */
      catalogVisibility: "public_listed" | "public_unlisted" | "private";
      /** @enum {string} */
      visibility: "public" | "instructors_only";
      isFrozen: boolean;
      /** Format: date-time */
      frozenAt?: string | null;
      frozenByUserId?: string | null;
      freezeReason?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** @description ä½œæˆè€…ãƒ¦ãƒ¼ã‚¶ãƒ¼IDï¼ˆinstructor or operator/root_operatorï¼‰ */
      createdByUserId: string;
      /** @enum {string} */
      status: "draft" | "pending_approval" | "active" | "archived";
      /** Format: date-time */
      approvalRequestedAt?: string | null;
      /** Format: date-time */
      approvedAt?: string | null;
      approvedByUserId?: string | null;
    };
    CourseCreateRequest: {
      title: string;
      description?: string;
      /** @deprecated */
      ownerUserId?: string;
      /** @enum {string} */
      catalogVisibility?: "public_listed" | "public_unlisted" | "private";
      /** @enum {string} */
      visibility?: "public" | "instructors_only";
      isFrozen?: boolean;
      /** Format: date-time */
      frozenAt?: string;
      frozenByUserId?: string;
      freezeReason?: string;
    };
    CourseUpdateRequest: {
      title?: string;
      description?: string;
      ownerUserId?: string;
      /** @enum {string} */
      catalogVisibility?: "public_listed" | "public_unlisted" | "private";
      /** @enum {string} */
      visibility?: "public" | "instructors_only";
      isFrozen?: boolean;
      /** Format: date-time */
      frozenAt?: string;
      frozenByUserId?: string;
      freezeReason?: string;
    };
    CourseMember: {
      id: string;
      courseId: string;
      userId: string;
      /** @enum {string} */
      role: "instructor_owner" | "learner" | "instructor" | "assistant";
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseMemberCreateRequest: {
      courseId: string;
      userId: string;
      /** @enum {string} */
      role: "instructor_owner" | "learner" | "instructor" | "assistant";
    };
    CourseMemberUpdateRequest: {
      courseId?: string;
      userId?: string;
      /** @enum {string} */
      role?: "instructor_owner" | "learner" | "instructor" | "assistant";
    };
    Lesson: {
      id: string;
      courseId: string;
      /** @enum {string} */
      type: "text" | "video" | "live" | "assignment";
      title: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    LessonCreateRequest: {
      courseId: string;
      /** @enum {string} */
      type: "text" | "video" | "live" | "assignment";
      title: string;
    };
    LessonUpdateRequest: {
      courseId?: string;
      /** @enum {string} */
      type?: "text" | "video" | "live" | "assignment";
      title?: string;
    };
    Assignment: {
      id: string;
      courseId: string;
      title: string;
      description?: string | null;
      /** Format: date-time */
      dueAt?: string | null;
      allowResubmission: boolean;
      isPublished: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    AssignmentCreateRequest: {
      courseId: string;
      title: string;
      description?: string;
      /** Format: date-time */
      dueAt?: string;
      allowResubmission?: boolean;
      isPublished?: boolean;
    };
    AssignmentUpdateRequest: {
      courseId?: string;
      title?: string;
      description?: string;
      /** Format: date-time */
      dueAt?: string;
      allowResubmission?: boolean;
      isPublished?: boolean;
    };
    CourseChannel: {
      id: string;
      courseId: string;
      /** @enum {string} */
      type: "assignment" | "one_on_one" | "announcement" | "general";
      /** @enum {string} */
      postingMode: "mixed" | "threads_only";
      /** @enum {string} */
      visibility: "public" | "instructors_only";
      isFrozen: boolean;
      /** Format: date-time */
      frozenAt?: string | null;
      frozenByUserId?: string | null;
      freezeReason?: string | null;
      name?: string | null;
      isManual: boolean;
      systemKey?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseChannelCreateRequest: {
      courseId: string;
      /** @enum {string} */
      type: "assignment" | "one_on_one" | "announcement" | "general";
      /** @enum {string} */
      postingMode?: "mixed" | "threads_only";
      /** @enum {string} */
      visibility?: "public" | "instructors_only";
      isFrozen?: boolean;
      /** Format: date-time */
      frozenAt?: string;
      frozenByUserId?: string;
      freezeReason?: string;
      name?: string;
      isManual?: boolean;
      systemKey?: string;
    };
    CourseChannelUpdateRequest: {
      courseId?: string;
      /** @enum {string} */
      type?: "assignment" | "one_on_one" | "announcement" | "general";
      /** @enum {string} */
      postingMode?: "mixed" | "threads_only";
      /** @enum {string} */
      visibility?: "public" | "instructors_only";
      isFrozen?: boolean;
      /** Format: date-time */
      frozenAt?: string;
      frozenByUserId?: string;
      freezeReason?: string;
      name?: string;
      isManual?: boolean;
      systemKey?: string;
    };
    CourseChannelMember: {
      id: string;
      channelId: string;
      courseMemberId: string;
      /** @enum {string} */
      status: "invited" | "joined" | "declined";
      /** Format: date-time */
      invitedAt?: string | null;
      /** Format: date-time */
      joinedAt?: string | null;
      /** Format: date-time */
      declinedAt?: string | null;
      lastReadMessageId?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseChannelMemberCreateRequest: {
      channelId: string;
      courseMemberId: string;
      /** @enum {string} */
      status?: "invited" | "joined" | "declined";
      /** Format: date-time */
      invitedAt?: string;
      /** Format: date-time */
      joinedAt?: string;
      /** Format: date-time */
      declinedAt?: string;
      lastReadMessageId?: string;
    };
    CourseChannelMemberUpdateRequest: {
      channelId?: string;
      courseMemberId?: string;
      /** @enum {string} */
      status?: "invited" | "joined" | "declined";
      /** Format: date-time */
      invitedAt?: string;
      /** Format: date-time */
      joinedAt?: string;
      /** Format: date-time */
      declinedAt?: string;
      lastReadMessageId?: string;
    };
    CourseThread: {
      id: string;
      channelId: string;
      /** @enum {string} */
      type: "submission" | "message_thread";
      rootMessageId?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseThreadCreateRequest: {
      channelId: string;
      /** @enum {string} */
      type: "submission" | "message_thread";
      rootMessageId?: string;
    };
    CourseThreadUpdateRequest: {
      channelId?: string;
      /** @enum {string} */
      type?: "submission" | "message_thread";
      rootMessageId?: string;
    };
    CourseThreadReadState: {
      id: string;
      threadId: string;
      courseMemberId: string;
      lastReadMessageId?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseThreadReadStateCreateRequest: {
      threadId: string;
      courseMemberId: string;
      lastReadMessageId?: string;
    };
    CourseThreadReadStateUpdateRequest: {
      threadId?: string;
      courseMemberId?: string;
      lastReadMessageId?: string;
    };
    CourseMessage: {
      id: string;
      channelId: string;
      threadId?: string | null;
      authorCourseMemberId?: string | null;
      text: string;
      isEmergency: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseMessageCreateRequest: {
      channelId: string;
      threadId?: string;
      authorCourseMemberId?: string;
      text: string;
      isEmergency?: boolean;
    };
    CourseMessageUpdateRequest: {
      channelId?: string;
      threadId?: string;
      authorCourseMemberId?: string;
      text?: string;
      isEmergency?: boolean;
    };
    CourseMessageAttachment: {
      id: string;
      courseMessageId: string;
      type: string;
      storageKey: string;
      fileName: string;
      mimeType: string;
      /** Format: int32 */
      size: number;
      /** Format: date-time */
      createdAt: string;
    };
    CourseMessageAttachmentCreateRequest: {
      courseMessageId: string;
      type: string;
      storageKey: string;
      fileName: string;
      mimeType: string;
      /** Format: int32 */
      size: number;
    };
    CourseMessageAttachmentUpdateRequest: {
      courseMessageId?: string;
      type?: string;
      storageKey?: string;
      fileName?: string;
      mimeType?: string;
      /** Format: int32 */
      size?: number;
    };
    CourseNotificationPreference: {
      id: string;
      courseMemberId: string;
      announcementNormalEnabled: boolean;
      submissionEnabled: boolean;
      submissionCommentEnabled: boolean;
      threadReplyEnabled: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseNotificationPreferenceCreateRequest: {
      courseMemberId: string;
      announcementNormalEnabled?: boolean;
      submissionEnabled?: boolean;
      submissionCommentEnabled?: boolean;
      threadReplyEnabled?: boolean;
    };
    CourseNotificationPreferenceUpdateRequest: {
      courseMemberId?: string;
      announcementNormalEnabled?: boolean;
      submissionEnabled?: boolean;
      submissionCommentEnabled?: boolean;
      threadReplyEnabled?: boolean;
    };
    CourseChannelNotificationPreference: {
      id: string;
      courseMemberId: string;
      channelId: string;
      muted: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseChannelNotificationPreferenceCreateRequest: {
      courseMemberId: string;
      channelId: string;
      muted?: boolean;
    };
    CourseChannelNotificationPreferenceUpdateRequest: {
      courseMemberId?: string;
      channelId?: string;
      muted?: boolean;
    };
    CourseEnrollment: {
      id: string;
      courseId: string;
      userId: string;
      /** @enum {string} */
      status: "applied" | "active" | "revoked";
      /** Format: date-time */
      grantedAt?: string | null;
      /** Format: date-time */
      revokedAt?: string | null;
      /** Format: date-time */
      paidAt?: string | null;
      /** @enum {string} */
      source: "stripe" | "manual";
      paymentId?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CourseEnrollmentCreateRequest: {
      courseId: string;
      userId: string;
      /** @enum {string} */
      status?: "applied" | "active" | "revoked";
      /** Format: date-time */
      grantedAt?: string;
      /** Format: date-time */
      revokedAt?: string;
      /** Format: date-time */
      paidAt?: string;
      /** @enum {string} */
      source?: "stripe" | "manual";
      paymentId?: string;
    };
    CourseEnrollmentUpdateRequest: {
      courseId?: string;
      userId?: string;
      /** @enum {string} */
      status?: "applied" | "active" | "revoked";
      /** Format: date-time */
      grantedAt?: string;
      /** Format: date-time */
      revokedAt?: string;
      /** Format: date-time */
      paidAt?: string;
      /** @enum {string} */
      source?: "stripe" | "manual";
      paymentId?: string;
    };
    Payment: {
      id: string;
      /** @enum {string} */
      provider: "stripe" | "manual";
      providerRef?: string | null;
      userId: string;
      courseId?: string | null;
      /** Format: int32 */
      amount: number;
      currency: string;
      /** @enum {string} */
      status: "pending" | "succeeded" | "failed" | "canceled" | "refunded";
      /** Format: date-time */
      paidAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    PaymentCreateRequest: {
      /** @enum {string} */
      provider?: "stripe" | "manual";
      providerRef?: string;
      userId: string;
      courseId?: string;
      /** Format: int32 */
      amount: number;
      currency?: string;
      /** @enum {string} */
      status?: "pending" | "succeeded" | "failed" | "canceled" | "refunded";
      /** Format: date-time */
      paidAt?: string;
    };
    PaymentUpdateRequest: {
      /** @enum {string} */
      provider?: "stripe" | "manual";
      providerRef?: string;
      userId?: string;
      courseId?: string;
      /** Format: int32 */
      amount?: number;
      currency?: string;
      /** @enum {string} */
      status?: "pending" | "succeeded" | "failed" | "canceled" | "refunded";
      /** Format: date-time */
      paidAt?: string;
    };
    Refund: {
      id: string;
      paymentId: string;
      providerRef?: string | null;
      /** Format: int32 */
      amount: number;
      /** @enum {string} */
      status: "pending" | "succeeded" | "failed" | "canceled";
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    RefundCreateRequest: {
      paymentId: string;
      providerRef?: string;
      /** Format: int32 */
      amount: number;
      /** @enum {string} */
      status?: "pending" | "succeeded" | "failed" | "canceled";
    };
    RefundUpdateRequest: {
      paymentId?: string;
      providerRef?: string;
      /** Format: int32 */
      amount?: number;
      /** @enum {string} */
      status?: "pending" | "succeeded" | "failed" | "canceled";
    };
    Coupon: {
      id: string;
      code: string;
      /** @enum {string} */
      discountType: "amount_fixed" | "amount_percent";
      /** Format: int32 */
      discountValue: number;
      currency?: string | null;
      /** Format: date-time */
      expiresAt?: string | null;
      /** Format: int32 */
      usageLimit?: number | null;
      /** Format: int32 */
      usedCount: number;
      isActive: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CouponCreateRequest: {
      code: string;
      /** @enum {string} */
      discountType: "amount_fixed" | "amount_percent";
      /** Format: int32 */
      discountValue: number;
      currency?: string;
      /** Format: date-time */
      expiresAt?: string;
      /** Format: int32 */
      usageLimit?: number;
      /** Format: int32 */
      usedCount?: number;
      isActive?: boolean;
    };
    CouponUpdateRequest: {
      code?: string;
      /** @enum {string} */
      discountType?: "amount_fixed" | "amount_percent";
      /** Format: int32 */
      discountValue?: number;
      currency?: string;
      /** Format: date-time */
      expiresAt?: string;
      /** Format: int32 */
      usageLimit?: number;
      /** Format: int32 */
      usedCount?: number;
      isActive?: boolean;
    };
    CouponRedemption: {
      id: string;
      couponId: string;
      userId: string;
      courseId?: string | null;
      paymentId?: string | null;
      /** Format: date-time */
      redeemedAt: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CouponRedemptionCreateRequest: {
      couponId: string;
      userId: string;
      courseId?: string;
      paymentId?: string;
      /** Format: date-time */
      redeemedAt?: string;
    };
    CouponRedemptionUpdateRequest: {
      couponId?: string;
      userId?: string;
      courseId?: string;
      paymentId?: string;
      /** Format: date-time */
      redeemedAt?: string;
    };
    AuditEvent: {
      id: string;
      /** Format: date-time */
      occurredAt: string;
      actorUserId: string;
      /** @enum {string} */
      actorGlobalRole: "guest" | "learner" | "instructor" | "assistant" | "operator" | "root_operator";
      /** @enum {string} */
      eventType: components["schemas"]["AuditEventType"];
      courseId?: string | null;
      channelId?: string | null;
      messageId?: string | null;
      reason: string;
      metaJson?: Record<string, unknown> | null;
      requestId?: string | null;
      ipHash?: string | null;
      userAgentHash?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    AuditEventCreateRequest: {
      /** Format: date-time */
      occurredAt?: string;
      actorUserId: string;
      /** @enum {string} */
      actorGlobalRole: "guest" | "learner" | "instructor" | "assistant" | "operator" | "root_operator";
      /** @enum {string} */
      eventType: "announcement_emergency_posted" | "course_frozen" | "course_unfrozen" | "channel_frozen" | "channel_unfrozen" | "dm_viewed_by_root_operator" | "course_created" | "course_approval_requested" | "course_approved" | "course_published" | "course_member_role_promoted" | "user_frozen" | "user_unfrozen";
      courseId?: string;
      channelId?: string;
      messageId?: string;
      reason: string;
      metaJson?: Record<string, never>;
      requestId?: string;
      ipHash?: string;
      userAgentHash?: string;
    };
    AuditEventUpdateRequest: {
      /** Format: date-time */
      occurredAt?: string;
      actorUserId?: string;
      /** @enum {string} */
      actorGlobalRole?: "guest" | "learner" | "instructor" | "assistant" | "operator" | "root_operator";
      /** @enum {string} */
      eventType?: "announcement_emergency_posted" | "course_frozen" | "course_unfrozen" | "channel_frozen" | "channel_unfrozen" | "dm_viewed_by_root_operator" | "course_created" | "course_approval_requested" | "course_approved" | "course_published" | "course_member_role_promoted" | "user_frozen" | "user_unfrozen";
      courseId?: string;
      channelId?: string;
      messageId?: string;
      reason?: string;
      metaJson?: Record<string, never>;
      requestId?: string;
      ipHash?: string;
      userAgentHash?: string;
    };
    Order: {
      id: string;
      userId: string;
      courseId: string;
      /** Format: int32 */
      amount: number;
      currency: string;
      /** @enum {unknown} */
      status: components["schemas"]["OrderStatus"];
      paymentProvider: string;
      paymentIntentId?: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    OrderCreateRequest: {
      userId: string;
      courseId: string;
      /** Format: int32 */
      amount: number;
      currency: string;
      /** @enum {string} */
      status: "pending" | "paid" | "cancelled" | "failed" | "refunded";
      paymentProvider: string;
      paymentIntentId?: string;
    };
    OrderUpdateRequest: {
      userId?: string;
      courseId?: string;
      /** Format: int32 */
      amount?: number;
      currency?: string;
      /** @enum {string} */
      status?: "pending" | "paid" | "cancelled" | "failed" | "refunded";
      paymentProvider?: string;
      paymentIntentId?: string;
    };
    OAuthIdentity: {
      id: string;
      userId: string;
      provider: string;
      providerUserId: string;
      email?: string | null;
      /** Format: date-time */
      lastLoginAt?: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    OAuthIdentityCreateRequest: {
      userId: string;
      provider: string;
      providerUserId: string;
      email?: string;
      /** Format: date-time */
      lastLoginAt?: string;
    };
    OAuthIdentityUpdateRequest: {
      userId?: string;
      provider?: string;
      providerUserId?: string;
      email?: string;
      /** Format: date-time */
      lastLoginAt?: string;
    };
    PasswordCredential: {
      id: string;
      userId: string;
      passwordHash: string;
      algorithm: string;
      /** Format: date-time */
      passwordUpdatedAt: string;
      isDisabled: boolean;
      /** Format: int32 */
      failedCount: number;
      /** Format: date-time */
      lastFailedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    PasswordCredentialCreateRequest: {
      userId: string;
      passwordHash: string;
      algorithm: string;
      /** Format: date-time */
      passwordUpdatedAt: string;
      isDisabled?: boolean;
      /** Format: int32 */
      failedCount?: number;
      /** Format: date-time */
      lastFailedAt?: string;
    };
    PasswordCredentialUpdateRequest: {
      userId?: string;
      passwordHash?: string;
      algorithm?: string;
      /** Format: date-time */
      passwordUpdatedAt?: string;
      isDisabled?: boolean;
      /** Format: int32 */
      failedCount?: number;
      /** Format: date-time */
      lastFailedAt?: string;
    };
    FileObject: {
      id: string;
      storageKey: string;
      bucket: string;
      fileName: string;
      mimeType: string;
      /** Format: int32 */
      size: number;
      checksum?: string | null;
      isScanned: boolean;
      isMalicious: boolean;
      createdByUserId?: string | null;
      /** Format: date-time */
      deletedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    FileObjectCreateRequest: {
      storageKey: string;
      bucket: string;
      fileName: string;
      mimeType: string;
      /** Format: int32 */
      size: number;
      checksum?: string;
      isScanned?: boolean;
      isMalicious?: boolean;
      createdByUserId?: string;
      /** Format: date-time */
      deletedAt?: string;
    };
    FileObjectUpdateRequest: {
      storageKey?: string;
      bucket?: string;
      fileName?: string;
      mimeType?: string;
      /** Format: int32 */
      size?: number;
      checksum?: string;
      isScanned?: boolean;
      isMalicious?: boolean;
      createdByUserId?: string;
      /** Format: date-time */
      deletedAt?: string;
    };
    Submission: {
      id: string;
      assignmentId: string;
      courseId: string;
      userId: string;
      threadId: string;
      /** Format: date-time */
      submittedAt: string;
      /** @enum {unknown} */
      status: components["schemas"]["SubmissionStatus"];
      /** Format: date-time */
      gradedAt?: string | null;
    };
    SubmissionCreateRequest: {
      assignmentId: string;
      courseId: string;
      userId: string;
      threadId: string;
      /** Format: date-time */
      submittedAt?: string;
      /** @enum {string} */
      status: "draft" | "submitted" | "returned" | "graded";
      /** Format: date-time */
      gradedAt?: string;
    };
    SubmissionUpdateRequest: {
      assignmentId?: string;
      courseId?: string;
      userId?: string;
      threadId?: string;
      /** Format: date-time */
      submittedAt?: string;
      /** @enum {string} */
      status?: "draft" | "submitted" | "returned" | "graded";
      /** Format: date-time */
      gradedAt?: string;
    };
    UserProfile: {
      id: string;
      userId: string;
      displayName: string;
      avatarFileObjectId?: string | null;
      bio?: string | null;
      isPublic: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UserProfileCreateRequest: {
      userId: string;
      displayName: string;
      avatarFileObjectId?: string;
      bio?: string;
      isPublic?: boolean;
    };
    UserProfileUpdateRequest: {
      userId?: string;
      displayName?: string;
      avatarFileObjectId?: string;
      bio?: string;
      isPublic?: boolean;
    };
    GradingComment: {
      id: string;
      courseId: string;
      threadId: string;
      authorUserId: string;
      targetUserId: string;
      body: string;
      /** Format: int32 */
      score?: number | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    GradingCommentCreateRequest: {
      courseId: string;
      threadId: string;
      authorUserId: string;
      targetUserId: string;
      body: string;
      /** Format: int32 */
      score?: number;
    };
    GradingCommentUpdateRequest: {
      courseId?: string;
      threadId?: string;
      authorUserId?: string;
      targetUserId?: string;
      body?: string;
      /** Format: int32 */
      score?: number;
    };
    SuccessResponse: {
      success: boolean;
    };
    ErrorResponse: {
      message: string;
      code?: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    LoginResponse: {
      accessToken: string;
      refreshToken: string;
    };
    RegisterRequest: {
      /** Format: email */
      email: string;
      password: string;
      name: string;
    };
    RegisterResponse: components["schemas"]["User"];
    RefreshResponse: {
      accessToken: string;
    };
    CheckoutRequest: {
      courseId: string;
      couponCode?: string;
    };
    CheckoutResponse: {
      sessionId: string;
      /** Format: uri */
      url: string;
    };
    Notification: {
      id: string;
      type: string;
      title: string;
      body?: string;
      isRead: boolean;
      /** Format: date-time */
      createdAt: string;
    };
    NotificationListResponse: {
      items: components["schemas"]["Notification"][];
    };
    CourseSideMenuResponse: {
      items: Record<string, never>[];
    };
    CursorPageInfo: {
      nextCursor?: string | null;
      hasMore: boolean;
    };
    OffsetPageInfo: {
      page: number;
      pageSize: number;
      total?: number | null;
    };
    ListMeta: {
      page?: components["schemas"]["OffsetPageInfo"];
      cursor?: components["schemas"]["CursorPageInfo"];
    };
    UserPublicView: {
      id: string;
      displayName: string;
      avatarUrl?: string | null;
    };
    FileObjectView: {
      file: components["schemas"]["FileObject"];
      url: string;
      mimeType?: string | null;
      size?: number | null;
    };
    MessageReactionView: {
      emoji: string;
      count: number;
      reactedByMe: boolean;
    };
    CourseMessageView: {
      message: components["schemas"]["CourseMessage"];
      sender: components["schemas"]["UserPublicView"];
      attachments: components["schemas"]["FileObjectView"][];
      reactions: components["schemas"]["MessageReactionView"][];
    };
    CourseChannelSummaryView: {
      channel: components["schemas"]["CourseChannel"];
      /** Format: date-time */
      lastMessageAt?: string | null;
      unreadCount: number;
    };
    CourseStatsView: {
      learnerCount: number;
      assignmentCount: number;
      lessonCount: number;
      activeChannelCount: number;
    };
    CourseSummaryView: {
      course: components["schemas"]["Course"];
      channelCount: number;
      memberCount: number;
      isFrozen: boolean;
    };
    CourseDetailView: {
      course: components["schemas"]["Course"];
      channels: components["schemas"]["CourseChannelSummaryView"][];
      stats: components["schemas"]["CourseStatsView"];
    };
    ThreadSummaryView: {
      threadId: string;
      rootMessage: components["schemas"]["CourseMessageView"];
      replyCount: number;
      /** Format: date-time */
      lastReplyAt?: string | null;
    };
    AssignmentSummaryView: {
      assignment: components["schemas"]["Assignment"];
      /** Format: date-time */
      dueAt?: string | null;
      status: string;
    };
    AssignmentDetailView: {
      assignment: components["schemas"]["Assignment"];
      mySubmission?: components["schemas"]["Submission"];
      rubric?: {
        [key: string]: unknown;
      } | null;
    };
    SubmissionView: {
      submission: components["schemas"]["Submission"];
      attachments: components["schemas"]["FileObjectView"][];
    };
    PaymentSummaryView: {
      payment: components["schemas"]["Payment"];
      course: components["schemas"]["Course"];
      buyer: components["schemas"]["UserPublicView"];
    };
    CourseListResponse: {
      items: components["schemas"]["CourseSummaryView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    CourseChannelListResponse: {
      items: components["schemas"]["CourseChannelSummaryView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    ThreadListResponse: {
      items: components["schemas"]["ThreadSummaryView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    MessageListResponse: {
      items: components["schemas"]["CourseMessageView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    AssignmentListResponse: {
      items: components["schemas"]["AssignmentSummaryView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    PaymentListResponse: {
      items: components["schemas"]["PaymentSummaryView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    GenericWriteRequest: {
      [key: string]: unknown;
    };
    GenericDetailView: {
      [key: string]: unknown;
    };
    GenericListResponse: {
      items: Record<string, never>[];
      meta?: components["schemas"]["ListMeta"];
    };
    OperatorAdminView: {
      [key: string]: unknown;
    };
    OperatorListResponse: {
      items: components["schemas"]["OperatorAdminView"][];
      meta?: components["schemas"]["ListMeta"];
    };
    UserMeView: components["schemas"]["User"];
    CourseChannelDetailView: components["schemas"]["CourseChannel"];
    InstructorCourseCreateRequest: {
      title: string;
      description?: string;
      /** @enum {string} */
      catalogVisibility?: "public_listed" | "public_unlisted" | "private";
      /** @enum {string} */
      visibility?: "public" | "instructors_only";
    };
    /** @enum {string} */
    GlobalRole: "guest" | "learner" | "instructor" | "operator" | "root_operator";
    /** @enum {string} */
    OrderStatus: "pending" | "paid" | "cancelled" | "failed" | "refunded";
    /** @enum {string} */
    SubmissionStatus: "draft" | "submitted" | "returned" | "graded";
    /** @enum {string} */
    AuditEventType: "announcement_emergency_posted" | "course_frozen" | "course_unfrozen" | "channel_frozen" | "channel_unfrozen" | "dm_viewed_by_root_operator" | "course_created" | "course_approval_requested" | "course_approved" | "course_published" | "course_member_role_promoted" | "user_frozen" | "user_unfrozen" | "user_created" | "user_updated" | "user_deleted" | "operator_role_changed";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * プロフィール取得
   * @description ログイン中ユーザー自身の基本情報を取得する。
   */
  API_001: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["UserMeView"];
        };
      };
    };
  };
  /**
   * プロフィール更新
   * @description プロフィール情報を更新する。
   */
  API_002: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * パスワード変更
   * @description パスワードを変更する。
   */
  API_003: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * 通知一覧取得
   * @description 自分宛の通知一覧を取得する。
   */
  API_004: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * 通知既読化
   * @description 指定した通知を既読にする。
   */
  API_005: {
    parameters: {
      path: {
        notificationId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * 通知一括既読
   * @description 全通知を一括既読にする。
   */
  API_006: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * 通知設定取得
   * @description 通知設定を取得する。
   */
  API_007: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * 通知設定更新
   * @description 通知設定を更新する。
   */
  API_008: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * 講座一覧取得
   * @description ストア公開講座一覧を取得する。
   */
  API_009: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseListResponse"];
        };
      };
    };
  };
  /**
   * 講座詳細取得
   * @description 講座の詳細情報を取得する。
   */
  API_010: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericDetailView"];
        };
      };
    };
  };
  /**
   * 講座申込(開始)
   * @description 講座への受講申込を開始する。
   */
  API_011: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * Stripeセッション生成
   * @description Stripe Checkoutセッションを生成する。
   */
  API_012: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckoutRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CheckoutResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * マイ講座一覧
   * @description 受講中の講座一覧を取得する。
   */
  API_013: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * 受講中講座詳細
   * @description 受講中講座の詳細を取得する。
   */
  API_014: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 決済/申込状況確認
   * @description 受講申込・決済の状況を確認する。
   */
  API_015: {
    parameters: {
      path: {
        enrollmentId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericDetailView"];
        };
      };
    };
  };
  /**
   * サイドメニュー取得
   * @description コース内サイドメニューを取得する。
   */
  API_016: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * 自分の課題一覧
   * @description 自分の課題一覧を取得する。
   */
  API_017: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AssignmentListResponse"];
        };
      };
    };
  };
  /**
   * 課題詳細取得
   * @description 課題の詳細情報を取得する。
   */
  API_018: {
    parameters: {
      path: {
        lessonId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["AssignmentDetailView"];
        };
      };
    };
  };
  /**
   * 課題提出
   * @description 課題を提出する。
   */
  API_019: {
    parameters: {
      path: {
        lessonId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["SubmissionView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 学習実績取得
   * @description 学習実績を取得する。
   */
  API_020: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * カレンダー取得
   * @description カレンダー情報を取得する。
   */
  API_021: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * コース修了処理
   * @description コースの修了を申請する。
   */
  API_022: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * アンケート取得
   * @description アンケートを取得する。
   */
  API_023: {
    parameters: {
      path: {
        surveyId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericDetailView"];
        };
      };
    };
  };
  /**
   * アンケート回答
   * @description アンケートに回答する。
   */
  API_024: {
    parameters: {
      path: {
        surveyId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 自講座一覧
   * @description 講師として管理する講座一覧を取得する。
   */
  API_025: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseListResponse"];
        };
      };
    };
  };
  /**
   * 講座新規作成（講師）
   * @description 講師がコースを新規作成する。
   */
  API_026: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InstructorCourseCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * 講座詳細取得(管理)
   * @description 講師管理用の講座詳細を取得する。
   */
  API_027: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * 講座情報更新
   * @description 講座情報を更新する。
   */
  API_028: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CourseUpdateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 講座削除(論理)
   * @description 講座を論理削除する。
   */
  API_029: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * 承認申請
   * @description 講座の公開承認を申請する。
   */
  API_030: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * コース公開（講師）
   * @description 承認済み講座を公開する。
   */
  API_031: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Forbidden (ownerUserIdä¸ä¸€è‡´) */
      403: {
        content: never;
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 売上分析サマリ
   * @description 売上分析サマリを取得する。
   */
  API_032: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * 振込先銀行設定
   * @description 振込先銀行口座を設定する。
   */
  API_033: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * シラバス構造取得
   * @description シラバス構造を取得する。
   */
  API_034: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * セクション追加
   * @description セクションを追加する。
   */
  API_035: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * セクション編集
   * @description セクションを編集する。
   */
  API_036: {
    parameters: {
      path: {
        sectionId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * セクション削除
   * @description セクションを削除する。
   */
  API_037: {
    parameters: {
      path: {
        sectionId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * レッスン作成
   * @description レッスンを作成する。
   */
  API_038: {
    parameters: {
      path: {
        sectionId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * レッスン詳細取得
   * @description レッスン詳細を取得する。
   */
  API_039: {
    parameters: {
      path: {
        lessonId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericDetailView"];
        };
      };
    };
  };
  /**
   * レッスン編集
   * @description レッスンを編集する。
   */
  API_040: {
    parameters: {
      path: {
        lessonId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * レッスン削除
   * @description レッスンを削除する。
   */
  API_041: {
    parameters: {
      path: {
        lessonId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * ライブ配信設定
   * @description ライブ配信設定を行う。
   */
  API_042: {
    parameters: {
      path: {
        lessonId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 提出一覧取得
   * @description 提出物一覧を取得する。
   */
  API_043: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * 評価・採点実行
   * @description 提出物の評価・採点を実行する。
   */
  API_044: {
    parameters: {
      path: {
        submissionId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SubmissionView"];
        };
      };
    };
  };
  /**
   * 受講者名簿取得
   * @description 受講者名簿を取得する。
   */
  API_045: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * 講座内ロール変更
   * @description コースメンバーのロールを変更する。
   */
  API_046: {
    parameters: {
      path: {
        courseId: string;
        userId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 受講権限剥奪
   * @description 受講権限を剥奪する。
   */
  API_047: {
    parameters: {
      path: {
        courseId: string;
        userId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * 受講者CSV出力
   * @description 受講者一覧をCSVエクスポートする。
   */
  API_048: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * チャンネル一覧取得
   * @description チャンネル一覧を取得する。
   */
  API_049: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseChannelListResponse"];
        };
      };
    };
  };
  /**
   * チャンネル作成
   * @description チャンネルを作成する。
   */
  API_050: {
    parameters: {
      path: {
        courseId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CourseChannelCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * チャンネル編集
   * @description チャンネルを編集する。
   */
  API_051: {
    parameters: {
      path: {
        channelId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseChannelDetailView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * チャンネル削除
   * @description チャンネルを削除する。
   */
  API_052: {
    parameters: {
      path: {
        channelId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * メッセージ履歴取得
   * @description メッセージ履歴を取得する。
   */
  API_053: {
    parameters: {
      path: {
        channelId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["MessageListResponse"];
        };
      };
    };
  };
  /**
   * メッセージ投稿
   * @description メッセージを投稿する。
   */
  API_054: {
    parameters: {
      path: {
        channelId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CourseMessageCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseChannelDetailView"];
        };
      };
    };
  };
  /**
   * スレッド詳細取得
   * @description スレッド詳細を取得する。
   */
  API_055: {
    parameters: {
      path: {
        messageId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
  /**
   * スレッド返信投稿
   * @description スレッドに返信する。
   */
  API_056: {
    parameters: {
      path: {
        messageId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseMessageView"];
        };
      };
    };
  };
  /**
   * メッセージ削除
   * @description メッセージを削除する。
   */
  API_058: {
    parameters: {
      path: {
        messageId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * メッセージ編集
   * @description メッセージを編集する。
   */
  API_057: {
    parameters: {
      path: {
        messageId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["CourseMessageView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * リアクション追加
   * @description リアクションを追加する。
   */
  API_059: {
    parameters: {
      path: {
        messageId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseMessageView"];
        };
      };
      /** @description Locked (Course is frozen) */
      423: {
        content: never;
      };
    };
  };
  /**
   * スレッド一覧取得
   * @description スレッド一覧を取得する。
   */
  API_060: {
    parameters: {
      path: {
        courseId: string;
        channelId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ThreadListResponse"];
        };
      };
    };
  };
  /**
   * スレッド作成
   * @description スレッドを作成する。
   */
  API_061: {
    parameters: {
      path: {
        courseId: string;
        channelId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * スレッド内メッセージ一覧
   * @description スレッド内メッセージを取得する。
   */
  API_062: {
    parameters: {
      path: {
        courseId: string;
        channelId: string;
        threadId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["MessageListResponse"];
        };
      };
    };
  };
  /**
   * スレッド返信
   * @description スレッドに返信する。
   */
  API_063: {
    parameters: {
      path: {
        courseId: string;
        channelId: string;
        threadId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CourseMessageCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": components["schemas"]["CourseDetailView"];
        };
      };
    };
  };
  /**
   * Stripe Webhook
   * @description Stripe Webhookを受信する。
   */
  API_064: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenericWriteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  /**
   * ヘルスチェック
   * @description サーバーの死活監視。
   */
  API_065: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["GenericListResponse"];
        };
      };
    };
  };
}
